### ISSUE TITLE
g is not defined error

### ISSUE THREAD

**Issue by vinayakumarr** [lanl-ansi/PowerModels.jl#106]
Hi,
       I am trying to execute the codes of Test AC Power Flow and Test AC Optimal Power Flow from https://discourse.julialang.org/t/problem-in-power-flow-using-julia/1491/6. But it is showing that g is not defined i.e

 g = branch["g"] // g is not defiined 
 b = branch["b"] // b is not defiined 
 c = branch["br_b"] // it works
 tr = branch["tr"] // it works
 ti = branch["ti"] // ti is not defined
 tm = tr^2 + ti^2

Could you please tell how to correct this. Currently, i am using the from https://github.com/lanl-ansi/PowerModels.jl

**Comment by ccoffrin** [comment]
g and b are derived values from r and x.  This was leading to issues if users wanted to modify the network cases after loading the file.  As of v0.3.0 derived values are not stored in the network data data-structure.

I will attempt to post and updated version of the example in discourse.

**Comment by ccoffrin** [comment]
https://discourse.julialang.org/t/problem-in-power-flow-using-julia/1491/11
