### ISSUE TITLE
Inconsistencies in formulation of SOCP problem

### ISSUE THREAD

**Issue by ShahabTor** [lanl-ansi/PowerModels.jl#125]
I believe we have spotted two inconsistencies in PowerModels package:
1.	Type hierarchy:
In form\wr.jl
The “AbstractWRForm” is defined from the root “AbstractPowerFormulation” abstract type. To my understanding, this is not correct as the link between WR problem and conic problem is missing. So the following correction is needed:

@compat abstract type AbstractWRForm <: AbstractPowerFormulation end 
@compat abstract type AbstractWRForm <: AbstractConicPowerFormulation end

2.	The function relaxation_complex_product defined under relaxation_scheme.jl is defined as a quadratic constraint:
c = @constraint(m, c^2 + d^2 <= a*b)
which returns error. Note that the multiplication of the right side of the inequality makes it rotated SOC constraint. The fix is to rewrite the above statement as follows:

c = @constraint(m, norm([2*c;2*d;a-b]) <= a+b) 

Otherwise please let me know if there is another reasoning behind the current implementation and so it is developed as such on purpose?

**Comment by ccoffrin** [comment]
Currently the AbstractConicPowerFormulation is only used for the SDP model, which uses the conic formulation, as you suggest.  The AbstractWRForm is concerned with NLP models.  I have found that using the nlp form `c^2 + d^2 <= a*b` converges significantly faster on large problems in contrast to the `norm([2c;2d;a-b]) <= a+b`

You could add a new type `AbstractConicWRForm` if you would like to explore the two alternatives.

**Comment by ccoffrin** [comment]
@ShahabTor, I recently added this Julia package, https://github.com/lanl-ansi/PowerModelsAnnex.jl, for exploring model variants like this one.  This file provides an example of how to build such an extension on top of PowerModels, https://github.com/lanl-ansi/PowerModelsAnnex.jl/blob/master/src/form/wr.jl. 

Feel free to make a PR to the Annex, if you are exploring these model variants.

**Comment by ShahabTor** [comment]
@ccoffrin thanks for your kind help and support. I am working on my code, will make a pull request as soon as it is ready.
Cheers
