### ISSUE TITLE
Data Component Id Checks

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#131]
When data is read in for the first time, check the component ids so make sure nothing is missing.  For example, a generator or branch that references a bus that does not exists.

**Comment by ccoffrin** [comment]
This would go nicely with checks proposed in #51

**Comment by frederikgeth** [comment]
Yeah, on a related note, we already ran into such an issue with test case case3.m, with the dc line being connected between node 10 and 20. Pull request for corrected test case soon to come.

**Comment by ccoffrin** [comment]
Sorry about that, I added that bug in the test case to remind my self that the network was not tested for AC feasibility with this line. 😅 

Happy to change it, assuming you have tested feasibility.

**Comment by frederikgeth** [comment]
by the way, how compatible do you want the defined test cases to be w.r.t. matpower? E.g. case3.m doesn't work in matpower (line 70, escape chars?).

**Comment by ccoffrin** [comment]
See #134 for an answer to your btw.

**Comment by frederikgeth** [comment]
ok, great.
