### ISSUE TITLE
Consider Adding HVDC Line Flow Values in All Solutions

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#140]
@frederikgeth, @hakanergun after spending some time playing with some HVDC datasets today I am feeling like the dc flow values `pf`,`pt`,`qf`,`qt` should be included in all solutions, rather than be optional, like branch flow values.

Some background, the reason that branch flow values are optional (with the default being to omit them) is because the flow values are fully determined by the bus voltages, so as long as you have these you can recompute the flow values.  Additionally, adding in this _redundant_ flow information increase the solution data size by at least 2x.  So you save a significant amount of space by omitting them when you don't need them.

These dclines are different, they are more like dispatchable generators than flows that are fully determined by other variables.  To fully reconstruct the flow solution, you will always need these values.

Thoughts?

**Comment by frederikgeth** [comment]
To be honest, at first I was rather confused myself that the result Dict didn't include the flow results. I understand your choice regarding the solution data size. Nevertheless, for people new to PowerModels, this default may create some unnecessary confusion. I rather prefer a default setting which includes all flow results. In any case, returning the dcline results is a good idea.

Also, you can come up with approximations / relaxations where the flow results cannot be unique determined based on the limited dataset. E.g. a network flow relaxation of a case with parallel lines.

**Comment by ccoffrin** [comment]
Ok good to know.  I'll probably make this change to DC lines in https://github.com/lanl-ansi/PowerModels.jl/pull/139.

I am in favor of keeping solutions as simple as possible, but they do need to be revised (see, https://github.com/lanl-ansi/PowerModels.jl/issues/77).  Right now the convention is that the solutions are always in the input data form (i.e. polar).  This is nice becouse it's standardized but it not clear how to best communicate things like the values of auxiliary variables, such as those by relaxations.
