### ISSUE TITLE
Data Viewing Function

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#146]
@lroald suggested that we have a way of displaying the PowerModels data object in a matrix style for visual review.  This “matrix view”, should have the ability to focus in on the subset of data related to the solution and constraints (e.g. voltage magnitude and associated voltage bounds, with or without bus_type).  This view should also have the ability to show you only components with binding constraints.

**Comment by yeesian** [comment]
link-dropping:

- https://github.com/mlubin/15.093/blob/master/ieee_rts.ipynb
- https://github.com/mlubin/15.093/blob/master/3%20node.ipynb
