### ISSUE TITLE
Enable more OTS tests on Travis

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#15]
move some models over to open source integer solvers, such as Pajarito.jl

**Comment by mlubin** [comment]
Give it a try,  the latest release should work in principle

**Comment by ccoffrin** [comment]
I ran into the issue that the models are MIQPs, so I was getting,

`ERROR: MethodError: 'LinearQuadraticModel' has no method matching LinearQuadraticModel(::Pajarito.PajaritoSolver)`

I resolved the issue by adding a redundant NLconstraint to the model.

If you agree LinearQuadraticModel is a strict sub-class of NonLinearModel, then this might be a case when Julia's "convert" idea could be useful.

**Comment by rb004f** [comment]
Have you posted this "error" to Miles?  Users of Jump really shouldn't have to do this...

**Comment by ccoffrin** [comment]
Miles fixed it here,

https://github.com/mlubin/Pajarito.jl/pull/110
