### ISSUE TITLE
Soultion.jl indexing

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/PowerModels.jl#152]
Given that the PowerModels data object has been refactored as an indexed map, should the index_name argument be dropped from the add_setpoint function? At the very least, make it an optional argument that defaults to the index_map key field?

**Comment by ccoffrin** [comment]
Good point.  Given the current data dict format, in `add_setpoint` the default value of `index_name` can be the value `"index"`, and then no methods will need to explicitly use this field.

Note #77, solution reporting is do for a rewrite.  This may happen as part of #150.
