### ISSUE TITLE
multinetwork bug?

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/PowerModels.jl#176]
In base.jl (buildref) function did you mean in line 201

https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/base.jl#L201 

```
haskey(data,"multinetwork") && data["multinetwork"]
```
instead of 

```
if data["multinetwork"]
```

In julia 6 this throws an exception if there is no field multinetwork in "data"

**Comment by ccoffrin** [comment]
I had imagined that the field `multinetwork` would be always required and must take a value true or false.  The current Matpower parser should ensure this.  This is open to discussion if you have a good motivation for making `multinetwork` optional.

**Comment by rb004f** [comment]
Depending on how much data has been processed up to this point in the code, ```mutilnetwork``` could be a calculated value. I am of the mind set that something like ```multinetwork``` is an optional field, but could be convinced otherwise.

I spent some time playing with the new multinetwork syntax, it feels a little unwieldy when working with a single network and makes the math a little less human readable, (i.e. pm.ref takes three arguments instead of 3).  I don't have a good solution (nor did I when I have tried to support multiple networks in other code architectures). The only thing I can think of is to have pm.ref[:buses] point at pm.ref[:nw][pm.cms][:buses], but maybe that is messy.

**Comment by ccoffrin** [comment]
Agree in the backend the multi-network encoding is tedious if you don't need it, but from the front end modeling I think it's pretty clean.  For example see,

https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/prob/opf.jl

If you don't explicitly specify a network it assumes the default one.

Also note all of the overloaded constraint template functions,

https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/constraint_template.jl

If no explicit network is specified, the current one is used as a default.

**Comment by ccoffrin** [comment]
Can you elaborate on the use case where the value of `multinetwork` would be computed?

**Comment by rb004f** [comment]
Yes, I like the way powermodels hides the multi-network aspects in the front end.  That works nicely.  I mainly found it tedious in building my own constraints (the back end), for example in gas-grid. But perhaps that is the right tradeoff... the modelers (front end) have a clean interface, but the developers (back end) have to live with something this so we can support multi-stage types of problems

**Comment by ccoffrin** [comment]
I am still not seeing how `multinetwork` can be an optional or a computed value.  Maybe it will be simpler to discuss in person?

if `multinetwork=false` then `data["bus"]` is valid and `data["nw"]` is invalid.
if `multinetwork=true` then `data["bus"]` is invalid and `data["nw"][<int>]["bus"]` is valid.

In the case of Matpower, it only supports one network, so implicitly it has a value `multinetwork=false`, which the parser makes explicit.

The `replicate` function provides a good example of transforming valid single network data into valid multinetwork data.

https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/data.jl#L96

**Comment by ccoffrin** [comment]
@rb004f is this clear at this point, esp. now that we setup the default semantics?  Can we close this issue?

**Comment by rb004f** [comment]
Yes, closing to now.
