### ISSUE TITLE
PSSE dict to PowerModels dict

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#212]
Translation function from the PSSE dict to the PowerModels dict.

**Comment by ccoffrin** [comment]
Regarding this feature, I recomend we implement it in two steps.  First focus on support for
- bus
- load
- shunt (fixed and switched)
- branch
- transformer (two-winding)
These features will cover the bulk of our test cases.

Once that is done and well tested, then then we can move on to,
- transformer (three-winding)
- HVDC lines

**Comment by ccoffrin** [comment]
Because PTI ids are complex, I also recommend adding a `pti_id` field to each PowerModels component.  To be compatible with JSON `pti_id` can be an array with a mix of ints and strings, which depend on the source component.

**Comment by pseudocubic** [comment]
bus, load, shunt, generator, branch, two-winding and three-winding transformers incl. magnetizing admittance are now supported. 

HVDC lines remaining
