### ISSUE TITLE
Add unit tests for PSSE features

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/PowerModels.jl#231]
- [x] Add unit tests for asymmetrical line charging added in #230 
- [x] Add unit tests for two-winding transformers with magnetizing admittance
- [x] Add unit tests for three-winding transformers
- [x] Add unit tests for three-winding transformers with magnetizing admittance
- [x] Add unit tests for two-terminal dc lines
- [x] Add unit tests for voltage source converter dc lines

Depends on #212

**Comment by ccoffrin** [comment]
@pseudocubic looks like a good time to revisit this, everything but dc lines is implemented.
