### ISSUE TITLE
PowerModels Data Extensions from PTI Data Files 

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#242]
Figure out how best to map the extended data (e.g. emergency voltage bounds) from PTI files into the PowerModels data structure.

**Comment by ccoffrin** [comment]
This sounds good for the near term.  Lets add an optional flag to `parse_file` for keeping all of the extra fields using the PTI names in lower case.

**Comment by ccoffrin** [comment]
@pseudocubic, I say this is done, agreed?

**Comment by pseudocubic** [comment]
Yes, I agree this is done for now. New issues can always opened when we want to make changes like we discussed last week with key renames
