### ISSUE TITLE
MultiConductor Data Checks

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#270]
Consider generalizing network data checks to support multiphase data.

**Comment by ccoffrin** [comment]
@pseudocubic was this addressed in #300 and #301?

**Comment by pseudocubic** [comment]
Not completely, but I am already in process of converting the rest of them and updating their tests, expect to see a new PR on Monday morning or so for that.

**Comment by ccoffrin** [comment]
Sounds good.

**Comment by pseudocubic** [comment]
Yes, forgot to add the closing command to that PR
