### ISSUE TITLE
Dispatch Implementation for MultiConductorValue

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#271]
Figure out how to implement dispatch for this type, then revise data functions that are currently using `map()`.

**Comment by ccoffrin** [comment]
Was this addressed by https://github.com/lanl-ansi/PowerModels.jl/pull/285?

**Comment by ccoffrin** [comment]
@pseudocubic, @frederikgeth, I am working on a PR for the revised data functions.  It seems like this is currently working.  Do you see any reason to keep this open?

**Comment by frederikgeth** [comment]
I think this can be closed
