### ISSUE TITLE
JuMP Direct Mode

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#275]
See if there is any need to consider using JuMP direct mode and/or expose this as parameter.

**Comment by ccoffrin** [comment]
@odow curious about your thoughts on this?  Is there any clear reason / value to adding support for this?

**Comment by odow** [comment]
I don't see a need. Obviously, no one has ever complained or requested this in the last five years...

**Comment by odow** [comment]
Previously, it wasn't super useful because Ipopt and the conic solvers didn't support direct mode. But the new nonlinear + Ipopt will. I don't think it makes much of a difference though. It might just lower memory usage.

**Comment by ccoffrin** [comment]
If memory savings are on the order of 2x, I can imagine a few uses cases.  Am I correct in that to use direct mode all one needs to do is initialize the jump model with `model = direct_model(<solver here>)`?

If so then the user provided `jump_model` parameter may be an easy way that users can already use InfrastructureModels in direct mode. See, https://github.com/lanl-ansi/InfrastructureModels.jl/blob/master/src/core/base.jl#L43-L103 and https://github.com/lanl-ansi/InfrastructureModels.jl/blob/master/src/core/base.jl#L378-L414

**Comment by odow** [comment]
> If memory savings are on the order of 2x

Yes, about that. (At least for model construction. Peak usage improvement somewhat less once you take the solvers workspace into account.)

> Am I correct in that to use direct mode all one needs to do is initialize the jump model with model = direct_model(<solver here>)

Yes, with the subtle distinction that the solver must be instantiated, as opposed to a constructor. So `direct_model(Ipopt.Optimizer())`, not `direct_model(Ipopt.Optimizer)`.
