### ISSUE TITLE
Discrepancy in run_opf and run_opf_bf

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#278]
Need to check why `run_opf / SOCWRPowerModel` and `run_opf_bf / SOCDFPowerModel` are producing different results on the `data/matpower/case5_gap.m` test case.  Guessing that this is related to the 4D cut constraint.

@frederikgeth, I won't have time to look into this for a while.  A PR is welcome.

**Comment by frederikgeth** [comment]
Interesting, hopefully I can take a look a week or so.

**Comment by frederikgeth** [comment]
Summarizing the current implementation, you might still get different results because BIM calls 'cut_complex_product_and_angle_difference' whereas BFM does not.

**Comment by ccoffrin** [comment]
This issue is now complete, thanks!  The final point is captured by #244.
