### ISSUE TITLE
Non-Convex PWL Cost Functions

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#287]
Add support for non-convex PWL cost functions.

https://github.com/GridMod/RTS-GMLC

can provide a suitable test case.

**Comment by ccoffrin** [comment]
As discussed in #350, https://github.com/GridMod/RTS-GMLC is actually convex and currently working.  

Support for this feature can be delayed until further notice.

**Comment by mjamei19** [comment]
@ccoffrin Can we discuss different options to add this feature and I can work on this issue? Some ISOs have offer curves like the one in the attachment which make the OPF run to fail due to non-convex cost functions. 
![screen shot 2019-02-12 at 11 57 14](https://user-images.githubusercontent.com/15697355/52636725-528e4000-2ec5-11e9-99c5-1659f67b7c4f.png)

**Comment by ccoffrin** [comment]
Sure thing.

The first step is to modify this function, 

https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/objective.jl#L415

So that it tracks which PWL functions are convex and which are not.  For the non-convex cases, binary variables need to be added for each segment and an SOS constraint needs to be added to enforce that only one segment is active at a time.

This function provides an example of adding variables and constraints while building the objective function,

https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/objective.jl#L146

**Comment by wenglerjoe** [comment]
I would like to ask if there was any development on this front?

I am currently using PowerModels and I came up with a problem where I actually have only concave piecewise linear cost curves and I dont know how to handle them

Thanks in advance for your help

**Comment by ccoffrin** [comment]
Hi @wenglerjoe, there has been no progress on this front so far.  My recommendation would be to build your own variant of the OPF problem specification where you replace the objective function with your own implementation that supports non-convex PWL costs via an SOS1 or SOS2 constraint.

**Comment by ccoffrin** [comment]
A PR to PowerModels or PowerModelsAnnex is of-course welcome if you would like to contribute your implementation back to the community.

**Comment by ccoffrin** [comment]
Closing due to low demand for this feature.  Adding support to PowerModelsAnnex would be a good idea.
