### ISSUE TITLE
Use of parser_test_i.raw

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#290]
It seems that `parser_test_i.raw` is on longer used.  Should it be removed or added to an explicit test?

**Comment by pseudocubic** [comment]
It looks like this is used in `test/psse.jl` on lines 187-188

**Comment by ccoffrin** [comment]
Got it, for some reason my text searches could not find it.  Now that I see the goal of test, I am wondering if it falls into the same category as #292.  Are voltage bounds optional in the PTI v33 format?

**Comment by pseudocubic** [comment]
No, that bit was added to see if I could nominally support v32 which doesn't include them. It seemed like an easy add at the time and I had a couple of v32 PTI files that I was testing on.

**Comment by ccoffrin** [comment]
got ya, I'll close this then.
