### ISSUE TITLE
Extended Matpower Format - merging component data

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/PowerModels.jl#305]
The extended matpower format only supports adding new data to standard matpower components (buses, generators, and branches).

**Comment by ccoffrin** [comment]
@rb004f, shall we close this issue or is this still a feature you would like to see?

**Comment by rb004f** [comment]
I suggest leaving it open as a minor issue.  For most components, we don't need a merge - just define the components in a single matlab table.  However, for the "special" PowerModels.jl component types (loads, shunts, and ne_branches), we can not currently augment the data through the extended matpower format.

**Comment by ccoffrin** [comment]
Closing in favor of https://github.com/lanl-ansi/PowerModels.jl/issues/840 which explains the challenge in a bit more detail.
