### ISSUE TITLE
Copyedit Mathematical Model Docs

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#306]
Double check this is reasonable, 

https://github.com/lanl-ansi/PowerModels.jl/blob/master/docs/src/math-model.md

**Comment by pseudocubic** [comment]
Are these correct?

    & S_{ij} = \left( Y_{ij} + {Y^c}_{ij}\right)^* \frac{|V_i|^2}{|{T}_{ij}|^2} - Y^*_{ij} \frac{V_i V^*_j}{{T}_{ij}} \;\; \forall (i,j)\in E \\
    & S_{ji} = \left( Y^*_{ij} + {Y^c}_{ji} \right)^* |V_j|^2 - Y^*_{ij} \frac{V^*_i V_j}{{T}^*_{ij}} \;\; \forall (i,j)\in E \\

Specifically, the second `Y^*_{ij}` in `S_{ji}`, should it be just `Y_{ij}`?

Otherwise, it looks reasonable to me.

**Comment by ccoffrin** [comment]
Good catch, thanks!
