### ISSUE TITLE
File Parsing Enhancements 

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#310]
- [ ] Update `parse_file` to follow the Julia io conventions; namely, it should be a special case of reading data from an io stream.
- [ ] Improve the Matpower export tests to work on in memory string data instead of files.
- [ ] move matpower_export tests from `test/data.jl` to `test/matpower.jl`.

@yeesian, interested at taking a hack at this?

**Comment by yeesian** [comment]
> Update `parse_file` to follow the Julia io conventions; namely, it should be a special case of reading data from an io stream.

I'm not sure this will be possible in general, because there is no way of disambiguating between a matpower or pss(r)e or json iostream. But it can happen at the `parse_matpower`, `parse_psse` and `parse_json` level, if that's okay with you?

**Comment by yeesian** [comment]
Linking https://github.com/lanl-ansi/PowerModels.jl/pull/78/files#r197114518 here since it's relevant

**Comment by yeesian** [comment]
Do we have any test cases for `parse_json`? https://github.com/lanl-ansi/PowerModels.jl/pull/215/files#r197120794

**Comment by yeesian** [comment]
> Update parse_file to follow the Julia io conventions; namely, it should be a special case of reading data from an io stream.

What should the behavior (for iostreams) be for code that relies on filenames? e.g. https://github.com/lanl-ansi/PowerModels.jl/commit/9f57db342d519ac27fd85d7bf546b39b94c7861d#r29449640

**Comment by ccoffrin** [comment]
You are correct that doing the disambiguation is not easy.  The natural solutions to me are to have different parse functions like, `parse_matpower(io, stream), parse_psse(io, stream)` or to have an extra argument in a a generic `parse(io, stream, id)` which specifies which to use.

Quite possibly we do not have a test for `parse_json` yet.  This can be tested by loading in a Matpower case, then turning it into a JSON string.

In the short term, we should make the case name an argument that is passed the existing functions, in the case of a stream that name can have a default value like `"stream"`, in the long run we can consider making case names an optional parameter.

**Comment by yeesian** [comment]
> The natural solutions to me are to have different parse functions like, parse_matpower(io, stream), parse_psse(io, stream) or to have an extra argument in a a generic parse(io, stream, id) which specifies which to use.

It's not clear that `parse_file(filetype, filename)` is much of an improvement over `parse_[filetype](filename)`. I'll push a branch for you to review soon.

**Comment by ccoffrin** [comment]
For user friendliness there should be a special case of `parse_file(filename)` which looks at the file extension and then dispatches to the correct variant.

**Comment by andrewrosemberg** [comment]
I'm sorry for commenting on a closed issue, but I had a small difficulty when parsing a powermodel case from a json string. 

I loaded a Matpower case, then turned it into a JSON string. The problem was with the version on 'case["source_version"]': when parsed to json It was dismantled into a dict containing [major,minor,patch,prerelease,build] fields. Therefor to return to the correct dictionary I had to make it into a version object once again.

My solution:
```julia
case = parse_json(file);
case["source_version"] = VersionNumber(case["source_version"]["major"],case["source_version"]["minor"],case["source_version"]["patch"],Tuple{}(case["source_version"]["prerelease"]),Tuple{}(case["source_version"]["build"]))
```
Maybe there is a more efficient solution, but this one is working fine so far. Hope this is of any help.

**Comment by yeesian** [comment]
This was brought up in https://github.com/lanl-ansi/PowerModels.jl/pull/461#discussion_r251871103 and we have since opened an issue for it in #462

**Comment by ccoffrin** [comment]
@andrewrosemberg, thanks for the comment.  In the short term I don't think any of the PowerModels code requires this version info, are you able to ignore it as well?

**Comment by andrewrosemberg** [comment]
@ccoffrin and @yeesian thank you for the answer and sorry for commenting on the wrong issue.
Yes, I'm able to ignore it, thank you!
