### ISSUE TITLE
MultiPhaseMatrix issue

### ISSUE THREAD

**Issue by frederikgeth** [lanl-ansi/PowerModels.jl#313]
Hi, I noticed some inconsistency in left vs right multiply w.r.t a MultiPhaseMatrix. Is this expected behavior? I'm not familiar enough with Julia to decipher the code [here](https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/multiphase.jl#L58)

```
julia> a = PowerModels.MultiPhaseVector(1.0, 3)
[1.0, 1.0, 1.0]

julia> diagm(a)*3.3
[3.3 0.0 0.0; 0.0 3.3 0.0; 0.0 0.0 3.3]

julia> 3.3*diagm(a)
ERROR: MethodError: no method matching *(::Float64, ::PowerModels.MultiPhaseMatrix{Float64})
```

**Comment by ccoffrin** [comment]
It looks like a bug to me, @pseudocubic do you agree?  A quick fix is to do all of your matrix operations in Julia arrays and only at the last moment put them into the MultiPhase object.

Also, still looking for a good solution to this, https://discourse.julialang.org/t/developing-pass-through-types/10717

**Comment by pseudocubic** [comment]
Not exactly a bug so much as its just a limitation of the way I extended these types. I can try to fix it, but if you have some idea about the proper way to extend these operators by all means let me know. In the meantime, @ccoffrin's suggestion that you do the operations using Julia arrays first and make the result a MultiPhaseValue last is the way to go.

**Comment by frederikgeth** [comment]
Thanks, no worries, this is very easy to work around :)
