### ISSUE TITLE
Confusing behavior when using conic formulation

### ISSUE THREAD

**Issue by frederikgeth** [lanl-ansi/PowerModels.jl#334]
If the bounds on a generator's output are not set, and if you use a conic formulation, it ends up defining a variable with a lower bound of infinity. I feel a warning or error would be more appropriate.

https://github.com/lanl-ansi/PowerModels.jl/blob/bf63d62962b7b31b615fe7282c668af2f3856b38/src/core/objective.jl#L123

I can do a PR later, it's easy to work around.

**Comment by ccoffrin** [comment]
Interesting point.  I would fix it as follows,
```
 lowerbound = min(0, ref(pm, n, :gen, i, "pmin", c)^2), 
```

**Comment by frederikgeth** [comment]
PR #348 addresses this issue right? The case `-\infty <= pg <= \infty` that I ran into now results in a lower bound of zero for `pg_sqr`.

**Comment by ccoffrin** [comment]
I think so, but you should double check.  :-)

**Comment by frederikgeth** [comment]
I confirm I don't have the problem anymore. (Also, this situation where this bug appears doesn't occur anymore as the OpenDSS parser sets bounds for all generators now). I therefore close this issue.
