### ISSUE TITLE
check_thermal_limits on multiconductor networks

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/PowerModels.jl#338]
Discuss best implementation of `check_thermal_limits` for multiconductor networks, particularly with inactive conductors on a line.

**Comment by ccoffrin** [comment]
The current implementation does not have the correct semantics for multiple phases.  The simplest solution for now is to add a check that the incoming date is implicit single phase.  A good generalization will require some thought.

**Comment by ccoffrin** [comment]
Will this be resolved by the changes PowerModels v0.15?

**Comment by pseudocubic** [comment]
It looks like we are using correct_thermal_limits! in PMD without problem, but I don't know if calc_thermal_limits is working, I will do some tests. Note that there is a dangling reference to MultiConductorVector (commented out) in calc_thermal_limits

**Comment by ccoffrin** [comment]
Closing as PMD no longer depends on PM.
