### ISSUE TITLE
Solution Recovery Option

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#341]
Add an output setting for requesting to attempt to recover a feasible solution from optimization model.  This setting will be off by default.  Turning it on will call a `recover_solution` function in `build_solution`.  Similar to `get_solution`, `recover_solution` can be parameterized by formulation. `recover_solution` will take the populated solution dict and attempt to add additional values (e.g. voltage angles in an SOC relaxation).  `recover_solution` will also set a "feasible" flag, to indicate if the recovered solution is expected to be an approximation or true solution to the AC equations (e.g. rank 1 in the SDP relaxation).

**Comment by rb004f** [comment]
Should this capability be more general and live in InfrastructureModels?

**Comment by ccoffrin** [comment]
Quite possible, in other infrastructure systems are you aware of algorithms that can be used to try and recover a feasible solution from the lifted variable space?

**Comment by ccoffrin** [comment]
Closing as this feature can now be implemented by solution post-processing functions.
