### ISSUE TITLE
ACTForm Reference

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#357]
Can you check these three other options for the ACTForm refrence and see if any of are a better fit.

A. Gomez Esposito and E. Ramos, “Reliable load flow technique for
radial distribution networks,” IEEE Transactions on Power Systems,
vol. 14, no. 3, pp. 1063–1069, Aug 1999.

E. Romero-Ramos, J. Riquelme-Santos, and J. Reyes, “A simpler and
exact mathematical model for the computation of the minimal power
losses tree,” Electric Power Systems Research,
vol. 80, no. 5, pp. 562–571, 2010.

F. Capitanescu, I. Bilibin, and E. Romero Ramos, “A comprehensive
centralized approach for voltage constraints management in active distribution
grid,” IEEE Transactions on Power Systems, 
vol. 29, no. 2, pp. 933–942, March 2014.

**Comment by frederikgeth** [comment]
There are two features that are unique to this formulation, right?
- `wr[(i,j)]^2 + wi[(i,j)]^2 == w[i]*w[j]` - nonconvex quadratic 
- `wi[(i,j)] == tan(t[i] - t[j])*wr[(i,j)]` - nonconvex nlp

Using these to qualify the papers, some observations following a quick reading:
- Capitanescu's and Romero-Ramos' papers don't include the tangent constraint, but they do solve the non-convex quadratically constrained optimisation problem, which is exact only in radial grids.
- Gomez Espisoto and Ramos' paper is the oldest, includes the tangent expression, but I think they only use it for post-processing. Furthermore, it is only presented in the context of power flow not OPF. This one may be worth mentioning though as it does completely describe the core mathematical model.
- The Jabr paper may be the oldest one I've seen that has a representation of the tangent constraint in an optimisation model (through the Taylor series expansion of it) for a meshed grid? Nevertheless, he does perform the SOC relaxation of the quadratic expression to solve it.

**Comment by ccoffrin** [comment]
Thanks for that.

Maybe the final answer is that this formulation is slightly novel and has not been studied in depth.  For now, Jabr seems like the most accurate reference.
