### ISSUE TITLE
Current Variable Naming

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#366]
Update `cm` to `ccm`.

**Comment by ccoffrin** [comment]
@frederikgeth, is this still an update you would like?

**Comment by ccoffrin** [comment]
@frederikgeth, bump.  If I recall the discussion on this point, the variable `cm` should be updated to `ccm` to reflect that we are considering the magnitude of a squared variable and to make room for the `cm,ca,cr,ci` that may come in due course.  Is that what you recall as well?

**Comment by frederikgeth** [comment]
Sorry I missed this! I recall the same thing, I still think this is a good approach.
