### ISSUE TITLE
SparseSDP Documentation

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#381]
Similar to `SDPWRMPowerModel`, `SparseSDPWRMPowerModel` would benefit from some documentation.

https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/form/wrm.jl#L148

@kersulis, I think you are best suited to select the best reference.

**Comment by BabakT1** [comment]
Hello, 
How can we get bus voltage values from the solution of SparseSDP?
I'm using "result=run_opf(network_data, SparseSDPWRMPowerModel, Mosek.Optimizer)
                  print_summary(result["solution"])"


Thanks,

**Comment by ccoffrin** [comment]
In general there is no way to recover consistent "bus voltage values" from a convex relaxation (there is a special case however if the SDP matrix is Rank 1).  In this case you can use the `w` values are on the buses as an approximation of the voltage magnitude squared if you like and some algorithms have been proposed for recovering an approximate from a relaxed solution but none are sufficiently simple to be explained in a few sentences.

For future reference, questions of this type are best discussed on Julia's discourse forum, https://discourse.julialang.org/c/domain/opt/13

**Comment by ccoffrin** [comment]
This is a good point the API is a little inconsistent in this regard.

They will appear in the diagonal elements of the WR matrices, but the mapping back to the bus ids can be non trivial.
