### ISSUE TITLE
Add new constraint to power models

### ISSUE THREAD

**Issue by mrnarimani** [lanl-ansi/PowerModels.jl#393]
I want to add a few new constraints to QCWRTriPowerModel type.  I have extended the test_case.m by adding a new matrix "mpc.branch_limit" which includes vdiff_min and vdiff_max (i.e., minimum and maximum voltage magnitude difference at neighboring buses). Following is one of those constraints that I wanna add to the type. Can you please let me know how I can do that? I put the following function in the code but it seems that it doesn't make any change. I do know that this constraint should tighten the QCWRTriPowerModel a little but it seems that it is bypassed during the compiling. I will appreciate any help!
```
    function constraint_voltage_magnitude_difference_neghboring_buses(pm::GenericPowerModel{QCWRTriForm}, n::Int, c::Int, f_bus, t_bus, vdiff_min, vdiff_max)

    vm_fr = var(pm, n, c, :vm, f_bus)
    vm_to = var(pm, n, c, :vm, t_bus)

       @constraint(pm.model, vm_fr - vm_to <= vdiff_max)
       @constraint(pm.model, vm_fr - vm_to >= vdiff_min)
     end
```

**Comment by ccoffrin** [comment]
Is your goal to add a feature to this package or is it just to make a modification for your own experimentation?

**Comment by mrnarimani** [comment]
My goal is representing power flow equations in another format and ultimately add it as a feature to PowerModels.

**Comment by ccoffrin** [comment]
Ok great.  I recommend starting with a PR to PowerModelsAnnex.  These file provide example of how to make extensions to the AC-OPF formulation. https://github.com/lanl-ansi/PowerModelsAnnex.jl/tree/master/src/pglib

**Comment by mrnarimani** [comment]
Thanks for the response! I have done all parts of this work (changing bound tightening part, adding variables, and defining constraints) in PowerModels.jl. My intuition is OBBT.jl is not compatible with PowerModelAnnex (Please correct me if I am wrong!).
The constraints that I have added to PowerModels take care of tightening the "Voltage magnitude difference" at neighboring buses. For instance, adding following constraint could improve the QC relaxation for different cases.  
```
@constraint(pm.model, v[i] - v[j] == vd[bp])
```
I added other constraints that I have derived for tightening "voltage magnitude difference" in the "constraint_voltage" but it seems that they get bypassed. 
Please let me know if you think I can resolve the issue by PowerModelsAnnex. Thanks in advance!

**Comment by mrnarimani** [comment]
Thank you so much!

**Comment by ccoffrin** [comment]
I recomend reviewing the github documentation for details about to debug your pull request.

This thread is currently not relating to PowerModels core, so I will close it.
