### ISSUE TITLE
Allow configuring Memento logger through PowerModels

### ISSUE THREAD

**Issue by kdheepak** [lanl-ansi/PowerModels.jl#402]
Currently in order to set the level of the logger in `PowerModels`, a user needs to install `Memento` in their environment. It would be useful if there was a function that was similar to the following in `PowerModels` (if it already doesn't exist):

```julia
import Memento	
# ...

function config_logger(;level="error")
    Memento.config!(Memento.getlogger("PowerModels"), level)	
end
```

This way a user would not need to install `Memento` but can still set the level of `PowerModels` appropriately by calling `PowerModels.config_logger()`.

**Comment by ccoffrin** [comment]
I'll consider a PR that adds this feature.  This is not a high priority for me because we will probably move from Memento to Julia standard logger, at which point we would drop support for configuring the logger from PowerModels.
