### ISSUE TITLE
Problems with new update

### ISSUE THREAD

**Issue by Franziska12345** [lanl-ansi/PowerModels.jl#412]
Hey, 
I updated my Packages yesterday and since then my OPF is not working anymore. After the command _using PowerModels_ Julia shows three errors. I suspect the new PowerModels-update to be the reason for this, but my low knowledge is also a possible cause. However, everything worked totally fine the last days and nothing changed but the updates. I am using Julia Version 0.6.4

julia> using PowerModels

INFO: Precompiling module PowerModels.

ERROR: LoadError: InitError: ArgumentError: Unknown time zone "America/Chicago"

ERROR: LoadError: Failed to precompile InfrastructureModels to C:\Users\xxx\.julia\lib\v0.6\InfrastructureModels.ji.

ERROR: Failed to precompile PowerModels to C:\Users\xxx\.julia\lib\v0.6\PowerModels.ji.

Maybe I need to update my Julia-Version? I am favoring version 0.6 though. I hope you can help me with my issuse. Thank you in advance!

**Comment by ccoffrin** [comment]
The current version of PowerModels should be working in v0.6/v0.7/v1.0.  A complete test log can be viewed here, https://travis-ci.org/lanl-ansi/PowerModels.jl/builds/450278778

The error `Unknown time zone "America/Chicago"` should be related to an upstream library, which may have changed recently.  My recommendation would be to try and rebuild your local Julia packages from scratch to see this resolves things.

**Comment by pseudocubic** [comment]
This is a problem with Memento / TimeZones (see https://github.com/invenia/Memento.jl/issues/104). My solution was to `Pkg.pin("TimeZones", v"0.8.0")`

**Comment by ccoffrin** [comment]
@Franziska12345 have any of these suggestions resolved your issue?  If so, lets close this issue.  If not, can you give us some more info on what is still breaking?

**Comment by Franziska12345** [comment]
I deleted everything and installed new. Then it worked. Thank you all for your help!
