### ISSUE TITLE
Capacity Extension for Generation Investment Planning

### ISSUE THREAD

**Issue by SabineAuer** [lanl-ansi/PowerModels.jl#430]
Dear developers of PowerModels.jl,

I am very new to PowerModels and interested in using it for investment planning, for which I need to undertake optimal power flow analysis with the possibility of capacity extension for all grid assets such as generators, inverters, transformers, lines etc. I've seen that there is a transmission planning functionality. However, is there a possibility to also optimize overall investment costs being constrained by powerflow? I am looking forward to your reply!

Cheers,
Sabine

**Comment by SabineAuer** [comment]
Thanks a lot for your fast reply. Generally I am a great fan of tools that are not black-box. Do you have any tutorials or minimal examples on how to undertake generation investment planning with PowerModels though?

**Comment by ccoffrin** [comment]
There is limited documentation for how to do this at the moment.  But I do my best to answer questions on a case-by-case basis.

The multi-network feature can be used to model multi time point OPF problems, see `post_mn_strg_opf` for an example.

This file provides some examples of formulating different sorts of problems in PowerModels,
- https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/prob/test.jl
- https://github.com/kaarthiksundar/n-k

These examples show what its like to build a Julia package that builds on PowerModels,
- https://github.com/hakanergun/PowerModelsACDC.jl
- https://github.com/frederikgeth/PowerModelsReliability.jl
- https://github.com/lanl-ansi/OPFRecourse.jl

One feature you would need for generator investment decisions is an on/off variant of the current generator model.  If it would be helpful, I could add a single time point OPF with UC decisions 
 an example of how that is implemented.

**Comment by ccoffrin** [comment]
@SabineAuer shall we close this issue or do you have something specific you would like done to address this?

**Comment by SabineAuer** [comment]
Thanks a lot for your reply! I will look more into the examples that you send. If you have the additional example how to "add a single time point OPF with UC decisions" available I would be happy to receive it. Otherwise if it is too much work for you, I would get back to you with more concrete questions when I looked through the previous examples you sent already. In any case I think we can close this issue.
