### ISSUE TITLE
Mismatch SOC BIM & BFM

### ISSUE THREAD

**Issue by hakanergun** [lanl-ansi/PowerModels.jl#433]
When I try to solve the case588_sdet from the pglib opf I get an inconsistency between the SOC BFM and SOC BIM, which should be the same.

The way I run the calculation is: 
I run the run_opf() function with SOCWRPowerModel which gives as result 374441.5456...., whereas when I run it with run_opf_bf() with the SOCBFPowerModel I get, 375161.4439....

When I looked into it a bit more I saw some more things:
(1) My first suspicion was that explicit current limits are needed for SOC BIM, as such I added the constraint: constraint_current_limit to the run_opf() function, which did not change the result of the SOC BIM solution.
(2) When I looked into bf.jl I saw that the constraint_branch_current is only defined for the from side of branches, but not for the to side, whereas for the constraint_current_limit() it is bidirectional. When I used the constraint_current_limit(), instead of constraint_branch_current in the bf formulation, then SOC BFM gives a more relaxed solution than the SOC BIM.

Do you have an idea where the inconsistency might come from?

On that note, I also saw that the check_current_limits() function is not called from the check_network_data() function within common.jl.

**Comment by hakanergun** [comment]
Hi Carleton,

Thanks for the advise. Indeed when I removed the upper bound on the current square variable in bf.jl and deactivated the 4D cuts (thus the cut_complex_product_and_angle_difference() constraint) in wr.jl in both cases I got as result: 37441.9509 SOCBFM and 374441.5456 for SOCBIM which is wihtin numerical accuracy I think. I guess that solves our issue @frederikgeth ;)

**Comment by ccoffrin** [comment]
Thanks for looking into that Hakan.  I'll close this issue because it seems to be a replicate of #244 at this point.
