### ISSUE TITLE
Slack bus in PowerModels

### ISSUE THREAD

**Issue by dawangbru** [lanl-ansi/PowerModels.jl#456]
I am sorry to put up a stupid question: in powermodels, could the slack bus slack the reactive power? or the slack bus only slacks the active power, like what MatPower does? Thanks a lot

**Comment by ccoffrin** [comment]
This is a good question and actually a subtle point.  If you doing a Power Flow study the slack bus will be a V/Theta-bus and will provide infinite active and reactive power.  If you are doing an Optimal Power Flow study, then the "slack bus" will only be used as a voltage angle "refrence bus" (i.e. theta=0), both active and reactive power will be within their bounds.  In fact, in an OPF study, the voltage angle refrence bus is independent of load and generator locations.

**Comment by dawangbru** [comment]
Thank you so much for the prompt and very useful answer! So in the OPF study, the reactive power generation at the slack bus is taken as unknown or known? That is to say, could the PowerModels assign the imbalance reactive power to the slack bus during the power flow iterations?

**Comment by ccoffrin** [comment]
In an AC-OPF study the power flow equations must be satisfied at every bus.  Reactive injection is known and is based on generator injection decision variables.

**Comment by ccoffrin** [comment]
I think this point has been addressed, can we close this issue?

Also, general questions / discussion about Julia and packages are best directed to https://discourse.julialang.org for the fastest response.

**Comment by dawangbru** [comment]
Thank you very much, ccoffrin, very helpful.
