### ISSUE TITLE
Issue with make_per_unit function on multi network data

### ISSUE THREAD

**Issue by kaarthiksundar** [lanl-ansi/PowerModels.jl#463]
The make_per_unit function is specific to the replicate function that is being used. In the test cases, the replicate function does deep copy of the single network data and hence, it works fine. If one decides to be memory efficient with the replicate function (by use of pointers), then the make_per_unit implementation would not give the desired effect; for instance, it would normalize pg values by pg/mvaBase^n. I do not know how to address this - but just bringing out the issue.

**Comment by kaarthiksundar** [comment]
Easy fix would be to make_per_unit and then replicate - but this just pushes to the issue to converting back to normal units.

**Comment by ccoffrin** [comment]
If `make_per_unit` works in the deep-copy case, then I don't think this is a bug.  If one is going to use clever space saving methods, then that user needs to be careful with their data manipulation.

A feature we could add to help streamline this would be to have an optional `per_unit` field in each component.  `make_per_unit` and `make_mixed_units` could then check this optional value before performing the requested conversion.

**Comment by kaarthiksundar** [comment]
I understand. The `per_unit` field in each component would be actually helpful.

**Comment by ccoffrin** [comment]
closing as a repeat of #682
