### ISSUE TITLE
issue with dictionaries of type `Dict{String, Any}` inside pm::PowerModels. 

### ISSUE THREAD

**Issue by mjamei19** [lanl-ansi/PowerModels.jl#466]
I am getting the following error when running power flow on my test case:
``
ERROR: MethodError: no method matching getval(::Dict{String,Real}, ::String, ::Int64)
Closest candidates are:
  getval(::Dict{String,Any}, ::String, ::Int64) at /Users/mahdijamei/.julia/packages/PowerModels/O1xQE/src/core/variable.jl:8
``.

The reason is in the test case that I have, the value of the keys in the pm["branch"] are `Dict{String,Real}` which makes sense as all the values are either `Int64`, `Float64`, or `Bool`. 
After discussing it with @eperim, we thought it might make sense to change the function argument to
`getval(::Dict{String,<:Any}, ::String, ::Int64)` according to the guidelines https://docs.julialang.org/en/v1/manual/types/#Parametric-Composite-Types-1  and also implementing the same thing for similar functions that can be affected.

**Comment by ccoffrin** [comment]
This is a good suggestion to make the code more flexible.  I will try to address this in the next week.

The quick fix would be to declare the type your Dict with `{String,Any}` explicitly to force `Dict{String,Any}` instead of `Dict{String,Real}`.

**Comment by ccoffrin** [comment]
@mjamei19 can you confirm that the master version is working for your situation?

**Comment by mjamei19** [comment]
@ccoffrin Thanks for the fix. Works just fine.
