### ISSUE TITLE
Norm form of branch current constraint

### ISSUE THREAD

**Issue by jay-dave** [lanl-ansi/PowerModels.jl#469]
Is there a tm missing in the norm form of constraint_branch_current? The constraint is located in bf.jl.

Corrected form -> 
`@constraint(pm.model, norm([2*p_fr; 2*q_fr; (w_fr/tm - cm/tm)]) <= (w_fr/tm + cm/tm))`

See attached derivation.
![norm_branchcurrent](https://user-images.githubusercontent.com/31774551/53734316-f4c99400-3e83-11e9-9c51-d907a44f8490.JPG)

**Comment by ccoffrin** [comment]
I think  so!  Thanks for commenting on this.  For consistency I would fix it like this,
```
@constraint(pm.model, p_fr^2 + q_fr^2 <= (w_fr/tm^2)*cm) # original
@constraint(pm.model, norm([2*p_fr; 2*q_fr; w_fr/tm - cm]) <= w_fr/tm + cm) # incorrect conic
@constraint(pm.model, norm([2*p_fr; 2*q_fr; w_fr/tm^2 - cm]) <= w_fr/tm^2 + cm) # correct conic
```
@frederikgeth, agreed?

**Comment by frederikgeth** [comment]
Great find, @jay-dave! I also prefer this form
```
@constraint(pm.model, norm([2*p_fr; 2*q_fr; w_fr/tm^2 - cm]) <= w_fr/tm^2 + cm)
```
as it makes it more obvious that the voltage variable is the one being rescaled.
