### ISSUE TITLE
Review Solution Collection Time

### ISSUE THREAD

**Issue by spmacdonald** [lanl-ansi/PowerModels.jl#478]
Hello,

I am trying to do an AC power flow on a large case that comes from an North American ISO.

I run:

`run_ac_pf(network_data, IpoptSolver(), setting = Dict("output" => Dict("branch_flows" => true)))`

An optimal solution is found, but then I get the warning:

`[warn | PowerModels]: there was an issue with getsolvetime() on the solver, falling back on @timed.  This is not a rigorous timing value.` 

And Julia seemingly hangs for a long time (5+ minutes, CPU @ 100%) before returning with no further output.

Full traceback is below.  

```
This is Ipopt version 3.12.10, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:  1367293
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:  2244396

Total number of variables............................:   322976
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:   321881
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  0.0000000e+00 6.87e+01 0.00e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  0.0000000e+00 6.35e+01 9.28e+02  -1.0 2.90e+01  -2.0 1.00e+00 1.00e+00h  1
   2  0.0000000e+00 1.16e+01 1.98e+02  -1.0 2.11e+01  -2.5 1.00e+00 1.00e+00h  1
   3  0.0000000e+00 9.44e+00 6.03e+01  -1.0 4.13e+01  -3.4 1.00e+00 1.00e+00h  1
   4  0.0000000e+00 1.14e+01 3.52e+01  -1.0 4.20e+01  -3.9 1.00e+00 1.00e+00h  1
   5  0.0000000e+00 2.65e+00 8.60e+00  -1.0 2.46e+01  -4.9 1.00e+00 1.00e+00h  1
   6  0.0000000e+00 4.78e-01 1.54e+03  -1.0 2.74e+01  -5.3 1.00e+00 1.00e+00H  1
   7  0.0000000e+00 2.67e-03 1.35e+01  -1.0 2.55e-01  -5.8 1.00e+00 1.00e+00h  1
   8  0.0000000e+00 1.68e-08 3.84e-04  -1.0 3.73e-03  -6.3 1.00e+00 1.00e+00h  1
   9  0.0000000e+00 5.39e-11 1.84e-13  -5.7 3.32e-08  -6.8 1.00e+00 1.00e+00h  1

Number of Iterations....: 9

                                   (scaled)                 (unscaled)
Objective...............:   0.0000000000000000e+00    0.0000000000000000e+00
Dual infeasibility......:   1.8396088184756757e-13    1.8396088184756757e-13
Constraint violation....:   7.3623340821028808e-14    5.3899067500862152e-11
Complementarity.........:   0.0000000000000000e+00    0.0000000000000000e+00
Overall NLP error.......:   1.8396088184756757e-13    5.3899067500862152e-11


Number of objective function evaluations             = 11
Number of objective gradient evaluations             = 10
Number of equality constraint evaluations            = 11
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 10
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 9
Total CPU secs in IPOPT (w/o function evaluations)   =     53.848
Total CPU secs in NLP function evaluations           =     13.892

EXIT: Optimal Solution Found.
[warn | PowerModels]: there was an issue with getsolvetime() on the solver, falling back on @timed.  This is not a rigorous timing value.
```

Thank you for your time&help.

**Comment by ccoffrin** [comment]
I have also noticed this recently and I am planning to have a faster PowerFlow solver in future releases.

There are two main sources of runtime before the model starts running in Ipopt,
- PowerModels pre-processing
- JuMP building the derivative oracles

Some recent features have made PowerModels pre-processing slow for large networks.  You can try removing this line to speed things up, https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/base.jl#L314. This should be addressed more generally here, https://github.com/lanl-ansi/PowerModels.jl/issues/263.

As for the derivative oracles, there is little PowerModels can do about that time, but it may be able to be improved in JuMP.  You can try using the "hessian-approx" option to Ipopt, so that it won't build the hessian oracles, but that will only work reliably if you have a very good starting point.

**Comment by ccoffrin** [comment]
Also note that `getsolvetime` is only used to measure the JuMP oracles build time and the time in the solver.

**Comment by spmacdonald** [comment]
I think this issue is separate from the pre-processing step.  Although to provide you a data point, the `dfs` method in `connected_components` throws a `StackOverflowError` on windows for this case.  Linux must have a higher recursion limit and it is able to finish after a few minutes.

The issue I am reporting here occurs after Ipopt returns: `EXIT: Optimal Solution Found.` there is at least 5-10 minutes (I have not timed it) after this message is printed before I get a `julia>` prompt again.

Or am I miss understanding your comment?

Thank you very much for your help.

**Comment by ccoffrin** [comment]
I see, I miss understood your point.

The only thing that is done after the solve time is solution collection.
It can take some time to collect the line flow values if the JuMP model
does not include branch flow variables.  If you can get by without line
flows it should be faster.

I can also look into speeding this up as well.

As a side note, Julia’s profiler is quite helpful in finding where the time
goes.

**Comment by hakanergun** [comment]
Hello,

I observe a similar issue if I use Atom; it takes quite a lot of time to load the result into the work space. If I use the Julia console, it works fine, though.

**Comment by spmacdonald** [comment]
I am running this from the console on Julia 1.1.0

**Comment by spmacdonald** [comment]
Regarding the branch flows, I am interested in some of them but not all.  Is it possible to specify an area or zone that you are interested in recording the branch flows for?

**Comment by ccoffrin** [comment]
Not currently, but it is an interesting idea.

https://github.com/lanl-ansi/PowerModels.jl/issues/480 is one feature that could be useful for this.  The work flow would be to solve the model with voltage output only an then compute flow values as a post-processing step.

**Comment by ccoffrin** [comment]
I think this issue has been addressed.  In v0.13.2 connectected component computation time was reduced and a dedicated DC-PF solver was added.  In v0.15 solution reporting should be near optimal in time (but might still take time to load into Atom).

@spmacdonald, any objections to closing?

**Comment by spmacdonald** [comment]
No objections, thanks for asking.
