### ISSUE TITLE
Compute Branch Flow Values

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#480]
It would be helpful to have a function that works on the data model can computes AC and DC branch flow values from a data model's voltage values.  This way optimize call only needs to return the voltage values and the flows can be computed afterwards as needed by the user.

In this case, the "branch flow" solver option would only need to be used to double check that the solvers' flow values are similar (or not) to those computed from the voltage values.

@frederikgeth, thoughts on this idea?

**Comment by spmacdonald** [comment]
Does this also mean that if one is starting from a solved case, when building the model you can compute the branch flows?  I believe this is what PowerWorld does when it reads in a case and it is a very useful feature.

**Comment by ccoffrin** [comment]
Yup, that would be the idea.

We might also consider a feature that computes power balance at the nodes, to check those are resonable as well.

**Comment by frederikgeth** [comment]
I think this is a good idea. Calculating flows based on the true AC power flow equations is perfectly reasonable. It can definitely lead to a bit of confusion in the context of relaxed formulations, as the relaxed power flow equations cannot be uniquely solved without additional information. 

So it needs to be clear that you're treating the voltages as if they were AC-feasible. This means that the solution can violate flow bounds, even if you modelled them in the relaxed formulation. 

Computing power balance on the nodes is very useful as well, but this goes in the direction of https://github.com/JuliaOpt/JuMP.jl/issues/693

**Comment by jd-lara** [comment]
@frederikgeth that's what we do in `PowerSimulations.jl`, we keep track of the balances at each node for all devices and then add those expressions to the network.
