### ISSUE TITLE
Storage Setpoint Data

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#487]
@frederikgeth, I think the storage component needs additional fields for describing it's injection into the network.  These would be needed to do for example load flow studies where the storage is not dispatchable.  These are implemented in the solution output as `ps`,`qs` values, but not currently included in the input data.

What do you think about adding these values to the data model?  Would it better to capture a different values (e.g. current magnitude instead of power?).

**Comment by frederikgeth** [comment]
Having a field for power flow values is useful indeed. But it'll be easy to define inconsistent inputs, unless you relax the bounds on the energy content or even remove the energy buffer equation  completely. I don't see a use case to define the fixed output in current variables, power seems reasonable.

**Comment by ccoffrin** [comment]
Sounds good.  I'll add `ps` and `qs` to the data spec in next breaking version.

I agree inconsistent values is a downside, but we have already crossed that bridge in all other components without major issues.  Still, a function that computes the amount of inconsistency of the state of the storage device would be useful.

**Comment by ccoffrin** [comment]
Once this is implemented the compute power balance function should be updated as well.
