### ISSUE TITLE
PTI Shunt Source Ids

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#511]
We should think about the best way to encode the shunt source ids so that it is clear if the shunt came from the "fixed" table or the "swiched" table.

**Comment by pseudocubic** [comment]
we could take a page from the TPPMs OpenDSS parser and for all the components have a string as the first part of the source_id naming the originating component

**Comment by ccoffrin** [comment]
That sounds like a good solution to me and a good standard for source_id in all of the infrastructure model packages.  Can you make a PR?  We will merge it for the next breaking release.

On a slightly tangential topic.  I have noticed that most of the time that I use "import_all", all I really want is the source ids.  What are your thoughts on always including them, or adding an option to just add source_id and not everything else?

**Comment by pseudocubic** [comment]
That's strange, as far as I know `source_id` should be available after import by default.
