### ISSUE TITLE
Always include source_id in parsed models

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#512]
@pseudocubic can you double check this?

**Comment by pseudocubic** [comment]
There is a unit test for this, confirming that `source_id` is included by default:

https://github.com/lanl-ansi/PowerModels.jl/blob/master/test/psse.jl#L419-L428

**Comment by ccoffrin** [comment]
Ok great.  I'll check my code that uses this feature.  Possibly we need a similar test for the Matpower parser.
