### ISSUE TITLE
TimeZones issue

### ISSUE THREAD

**Issue by doorals** [lanl-ansi/PowerModels.jl#528]
In Julia 1.1.1, JuMP v0.18.5, I get this error while adding the package: 
```
Building TimeZones → `~/.julia/packages/TimeZones/Z0kpK/deps/build.log`
┌ Error: Error building `TimeZones`: 
```
Fix will be helpful!

**Comment by ccoffrin** [comment]
This is an issue with an upstream dependency and I am not sure what causes it.  In the past I have resolved it by clearing and rebuilding my Julia environment, but there may be simpler solutions like `] update; ] build`.

Also you might try updating to JuMP v0.19 and the latest version of PowerModels.

**Comment by doorals** [comment]
@ccoffrin Thanks! update and build didn't help. It may be an issue with the compatibility of PowerModels with an older version of JuMP. Upgrading JuMP works though.

**Comment by ccoffrin** [comment]
Glad to hear it!
