### ISSUE TITLE
Function Name Updates

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#538]
PowerModels v0.12 will include some signficant function name changes that will require updates in downstream packages.  This includes both `_`  and `!` (#454).  As well as the following function naming updates.  If you don't like any names in the list below, please speak up in the next couple of days. 

CC: @rb004f @pseudocubic @kaarthiksundar @frederikgeth @sanderclaeys @hakanergun 

new_name - old_name
Core:
build_model - build_generic_model
optimize_model! - solve_generic_model
run_model - run_generic_model

Ref:
ref_add_core! - core_ref!
ref_add_connected_components! - cc_ref!
ref_add_on_off_va_bounds! - on_off_va_bounds_ref!
ref_add_ne_branch! - ne_branch_ref!

ref_calc_branch_flow_bounds - calc_branch_flow_bounds
ref_calc_storage_injection_bounds - calc_storage_injection_bounds
ref_calc_voltage_product_bounds - calc_voltage_product_bounds

Data and Parsing:
calc_connected_components - connected_components
calc_cost_pwl_lines - get_lines

comp_start_value - getval
conductor_value - getmcv

parse_psse - _pti_to_powermodels!

Models:
constraint_power_balance_shunt - constraint_kcl_shunt
constraint_power_balance_shunt_storage - constraint_kcl_shunt_storage
constraint_power_balance_shunt_ne - constraint_kcl_shunt_ne

cut_product_replicates - relaxation_tighten_vv

Solution:
solution_opf! - get_solution
solution_ots! - get_ots_solution
solution_tnep! - get_tnep_solution

add_setpoint_bus_demand! - add_bus_demand_setpoint
add_setpoint_bus_voltage! - add_bus_voltage_setpoint
add_setpoint_generator_power! - add_generator_power_setpoint
add_setpoint_generator_status! - add_generator_status_setpoint
add_setpoint_storage! - add_storage_setpoint
add_setpoint_branch_flow! - add_branch_flow_setpoint
add_setpoint_branch_status! - add_branch_status_setpoint
add_setpoint_dcline_flow! - add_dcline_flow_setpoint
add_setpoint_dcline_status! - add_branch_status_setpoint_dc

add_setpoint_branch_ne_flow! - add_branch_flow_setpoint_ne
add_setpoint_branch_ne_built! - add_branch_ne_setpoint

add_dual_kcl! - add_kcl_duals
add_dual_sm! - add_sm_duals

**Comment by ccoffrin** [comment]
Last call for name change requests.  Planning to tag v0.12 in about 24 hours.

**Comment by frederikgeth** [comment]
Looks good. The only thing that stood out for me was `cc_ref!` vs `calc_connected_components` (inconsistent use of abbreviation)

**Comment by ccoffrin** [comment]
Thanks @frederikgeth, I am not sure I follow what you are getting at,
`cc_ref!` added connected components information to ref and became `ref_add_connected_components!`.  `connected_components` computed connected components information from the data model and became `calc_connected_components`.  The prefix before `connected_components` is consistent with other functions performing similar tasks.

**Comment by frederikgeth** [comment]
sorry, looking back at it, my comment was a brainfart. Go ahead and merge
