### ISSUE TITLE
build_ref() on multinetworks

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/PowerModels.jl#541]
When using `build_ref()` on a multinetwork data structure, the top level information is not translated into the new data structure. 

```julia
import PowerModels
case = PowerModels.parse_file("test/data/matpower/case5_strg.m")
mn_case = PowerModels.replicate(case, 3)

case_ref = PowerModels.build_ref(case)
mn_case_ref = PowerModels.build_ref(mn_case)
```

In the above example, `case_ref` will contain `:baseMVA` and `:time_elapsed` within `case_ref[:nw][0]`, but neither of these keys exist in `mn_case_ref`, neither in the outer scope, nor copied to any of the data in `mn_case_ref[:nw]`

**Comment by pseudocubic** [comment]
CC @noahrhodes

**Comment by ccoffrin** [comment]
I looked into this.  The issue arrises from the fact that "time_elapsed" is currently treated as a global parameter.  In light of this example, I think a more flexible semantics will be to have a network-wise time_elapsed parameters in the context of multi-networks.  I am getting ready for the v0.12 release, so I will work it into that.

FYI @frederikgeth
