### ISSUE TITLE
test tnep example not working

### ISSUE THREAD

**Issue by faoh** [lanl-ansi/PowerModels.jl#545]
I try to use the case3_tnep.m and case5_tnep.m to see how the PowerModel build the network, but it shows 'ne_arcs' not found. 
pm = build_generic_model("case5_tnep.m", ACPPowerModel, PowerModels.post_tnep)
KeyError: key :ne_arcs not found
Is is the matpower case problem or I need to add something for this problem?
I also try to use run_tnep("case5_tnep.m",DCPPowerModel,with_optimizer(Ipopt.Optimizer))
No matter for AC or DC, it shows
MathOptInterface.UnsupportedConstraint{MathOptInterface.SingleVariable,MathOptInterface.ZeroOne}: `MathOptInterface.SingleVariable`-in-`MathOptInterface.ZeroOne` constraints is not supported by the model.
Do I use the wrong case or wrong solver?

**Comment by ccoffrin** [comment]
It sounds like your code may be out of sync with the latest PowerModels version.

For example,
```
pm = build_generic_model("case5_tnep.m", ACPPowerModel, PowerModels.post_tnep)
```
is now (as of v0.12),
```
pm = build_model("case5_tnep.m", ACPPowerModel, PowerModels.post_tnep, ref_extensions=[ref_add_on_off_va_bounds!,ref_add_ne_branch!], solution_builder = solution_tnep!)
```
As for the second error, you will need a Mixed-Integer solver for this problem.  Cbc and Juniper are reasonable free options.

**Comment by faoh** [comment]
So for the latest version, to build the generic model for all optimization problem, use the build_model?
However, with your script, I still get error message

MethodError: no method matching GenericPowerModel(::Dict{String,Any}, ::Type{StandardACPForm}; solution_builder=PowerModels.solution_tnep!)
Closest candidates are:
  GenericPowerModel(::Dict{String,#s112} where #s112, ::DataType; ext, setting, jump_model) at C:\PowerModels.jl-master\src\core\base.jl:61 got unsupported keyword argument "solution_builder". It seems like something wrong with the solution_builder.

As to Mix-integer problem, I use Juniper.Optimizer, but it shows MethodError: no method matching optimize_model!(::GenericPowerModel{StandardACPForm}, ::Type{Juniper.Optimizer}; solution_builder=PowerModels.solution_tnep!)
Closest candidates are:
  optimize_model!(::GenericPowerModel, !Matched::JuMP.OptimizerFactory; solution_builder) at C:\Documents\PowerModels.jl-master\src\core\base.jl:231

I am trying to get familiar with PowerModels, so I am trying some examples now
Thanks for your help.

**Comment by ccoffrin** [comment]
Sorry the first line should be,
```
pm = build_model("case5_tnep.m", ACPPowerModel, PowerModels.post_tnep, ref_extensions=[ref_add_on_off_va_bounds!,ref_add_ne_branch!])
```

As for the second point, are you sure you did `with_optimizer(Juniper.Optimizer(...))`it looks like you did not include the `with_optimizer` bit?

**Comment by faoh** [comment]
Thank you! Got it.
May I ask where is the detailed documentation of the PowerModels.jl?
I look the Home.PowerModels, but I didn't find the detailed example of script, like build_model.

**Comment by ccoffrin** [comment]
Great!

The core docs are here, https://lanl-ansi.github.io/PowerModels.jl/stable/

A tutorial is also available here, https://github.com/lanl-ansi/tutorial-grid-science-2019 although we are in the middle of updating it the latest version of JuMP and PowerModels at the moment.

**Comment by ccoffrin** [comment]
Shall we close this issue?

**Comment by faoh** [comment]
run_tnep("C:/Users/huan4/Documents/PowerModels.jl-master/test/data/matpower/case5_tnep.m",ACPPowerModel,with_optimizer(Juniper.Optimizer))

┌ Error: The option nl_solver has to be set i.e with nl_solver = Ipopt.Optimizer
└ @ Juniper C:\Users\huan4\.julia\packages\Juniper\DC0lg\src\solver.jl:91

**Comment by ccoffrin** [comment]
Setting up Juniper is along these lines,
```
ipopt_solver = JuMP.with_optimizer(Ipopt.Optimizer, tol=1e-6, print_level=0)
cbc_solver = JuMP.with_optimizer(Cbc.Optimizer, logLevel=0)
juniper_solver = JuMP.with_optimizer(Juniper.Optimizer, nl_solver=JuMP.with_optimizer(Ipopt.Optimizer, tol=1e-4, print_level=0), mip_solver=cbc_solver, log_levels=[])
```

**Comment by faoh** [comment]
Thanks!
We can close the issue
