### ISSUE TITLE
Interface constraint

### ISSUE THREAD

**Issue by spmacdonald** [lanl-ansi/PowerModels.jl#549]
How would you recommend I create a constraint to represent an interface.

By interface I mean a collection of lines where the the sum of the flow over the lines must be less than some limit.

If it matters I am primarily concerned with the DC model.

Thank you for your help

**Comment by ccoffrin** [comment]
It depends on how flexible you want the implementation to be.  A quick hack would be to do something like this,
```
data = PowerModels.parse_file("case.raw")
data["interface"] = [1,7,10] # these are the branch ids of the interface
data["interface_limit"] = 1.2 # this is the rate limit of the interface in p.u.
```
Then you need to add the constraint in the model.  For example in `post_opf` you could add,
```
interface_branch [ref(pm, :branch, id) for id in ref(pm, :interface)]
flow_ids = [(br["index"], br["f_bus"], br["t_bus"]) for br in interface_branch]
@constraint(pm.model, sum( var(pm, :p, fid) for fid in flow_ids) <= ref(pm, :interface_limit))
```

**Comment by spmacdonald** [comment]
That seems fairly straightforward, I will give it a shot.  Thanks!

**Comment by ccoffrin** [comment]
Great!  Can we close this issue?
