### ISSUE TITLE
'post_ots' breaks!

### ISSUE THREAD

**Issue by harshangrjn** [lanl-ansi/PowerModels.jl#550]
In PowerModels v0.12.1:
Solving an OTS problem using `run_ots(data, QCWRPowerModel, solver)` is fine. But `build_model(data, QCWRPowerModel, PowerModels.post_ots)` throws an error `ERROR: KeyError: key :off_angmin not found`. Looks like `PowerModels.build_ref` is not populating keys `:off_angmin` and ``:off_angmax``, specific for the OTS version of the problem.

**Comment by ccoffrin** [comment]
A new feature in PowerModels v0.12 was problem-based ref extentions.  In the OTS case you need to also have `ref_add_on_off_va_bounds!`.

Try `build_model(data, QCWRPowerModel, PowerModels.post_ots, ref_extensions=[ref_add_on_off_va_bounds!], solution_builder = solution_ots!)` and see if that resolves your issue.

**Comment by harshangrjn** [comment]
Thanks! 

Now I get this error: `got unsupported keyword argument "solution_builder"`. However without the `solution_builder`, it runs fine. But after `optimize_model!(model, solver)`, in the result, I am not able to extract the `br_status`.

**Comment by pseudocubic** [comment]
solution_builder should be used in either `run_model` or `optimize_model!`, see https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/base.jl#L230 or https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/base.jl#L180

**Comment by harshangrjn** [comment]
Thanks @pseudocubic! It all works now. Basically, solution_builder populates the `br_status`. May be some documentation on problem-based ref-extensions options will be helpful.
