### ISSUE TITLE
MathOptInterface support

### ISSUE THREAD

**Issue by asavasci** [lanl-ansi/PowerModels.jl#558]
I am getting a bunch of warning messages regarding MathOptInterface when I run the ] test PowerModel. The screen as
![image](https://user-images.githubusercontent.com/33552041/60923013-0248bd80-a26c-11e9-9c3d-a03d71d2dd32.png)
What version of JuMP should I use ?

**Comment by pseudocubic** [comment]
These are just warnings that can be safely ignored for now as long as all of the tests pass
