### ISSUE TITLE
Weird output running dc & ac pf in pmap()

### ISSUE THREAD

**Issue by jchen975** [lanl-ansi/PowerModels.jl#559]
I'm running a few thousand iterations of `run_dc_pf` and `run_ac_pf` by varying `PD`, `QD` fields of all loads in each iteration and extract the `vm` and `va` fields of the dc and ac results. This is basically an embarrassingly parallel problem so I restructured the serial code to run it with `pmap`. After running a simple test case, I *think* it works but when it terminates, the next `julia >` prompt doesn't appear unless I press Enter. Is this an expected behavior? 

Also the output is a little messed up due to the `From worker x` output of `pmap` on every line. As a result I can't really read the results of `run_dc_pf` and `run_ac_pf` and more importantly, `@time`. So I'm wondering if I can redirect all outputs to a text file for me to parse later, or run it with a non verbose option if it exists. 

I posted this on Discourse a few days ago but didn't get any replies, so I'd appreciate any help on this.

**Comment by ccoffrin** [comment]
Can you point me to the post you made in discourse?  I did a quick search but was not able to find it.

You can control the output using with commands like `PowerModels.slience()` and each solver has its own options, for example, `with_optimizer(Ipopt.Optimizer, tol=1e-6, print_level=0)`.  However, if you are using pmap, I would recomend making the function return the summary information that you may need or write the results to files, rather than using standard output.

**Comment by jchen975** [comment]
Thanks very much, I'll try them. So is `julia >` prompt not showing up after pmap run terminates a problem? This is the first time I'm using `pmap` as well so it could be something on my part. 
And the post is here:
https://discourse.julialang.org/t/powermodels-redirect-output-to-file-and-weird-output-behavior-using-pmap/26147

**Comment by ccoffrin** [comment]
Thanks for the link, I needed to change to sort order in discourse to be able to find the most recent posts!

As for the Julia prompt not showing up.  I have not noticed that, but the stdout stream is not synchronized print outs after the prompt can be expected.  I am generally running Julia as a script from the command line and I have had no issues there with pmap.

**Comment by ccoffrin** [comment]
Can we close this issue?
