### ISSUE TITLE
bus voltage bounds

### ISSUE THREAD

**Issue by ksun46** [lanl-ansi/PowerModels.jl#563]
I ran the AC rectangular formulation with 
```
case = "case13659pegase"
PowerModels.silence()
run_opf(string("data/$case/$case.m"), ACRPowerModel, with_optimizer(Ipopt.Optimizer))
```
The network has 13659 buses and 20467 branches (all active), and here is the summary of IPOPT
```
Total number of variables............................:   117370
                     variables with only lower bounds:        0
                variables with lower and upper bounds:   117370
                     variables with only upper bounds:        0
Total number of equality constraints.................:   109187
Total number of inequality constraints...............:   105502
        inequality constraints with only lower bounds:    32284
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:    73218
```
I believe the inequalities comes from lower and upper bounds on `vr^2+vi^2`, lower and upper bounds on angle difference, and upper bounds on thermal limit.
Since 
```
73218 - 20467 * 3 = 11817 [ub on thermal limit(both directions) and angle difference]
32284 - 20467 = 11817 [lb on angle difference]
```
It seems like only 11817/13659 buses have bounds on their voltage magnitude. Could anyone please explain is this correct? and where is bus voltage boundedness specified in the network data?

Thanks.

**Comment by ccoffrin** [comment]
The OPF follows the formulation that is discussed [here](https://lanl-ansi.github.io/PowerModels.jl/stable/math-model/).  All of the decision variables should have bounds.  In the ACRPowerModel the number of variables should be roughly 2*|buses| + 2*|branches| + 2*|generators|.

**Comment by ccoffrin** [comment]
All busses have bounds on voltage magentues but these are in the inequality constraint category.

**Comment by ksun46** [comment]
Thanks for the response. Yes, I understand that all variables are constructed with bounds. For this network, the total number of variables 
`117370 =2*|buses| + 4*|branches| + 2*|generators|`
where I guess 4 is due to real and reactive power on both directions. All of them are bounded. This matches the IPOPT summary. 

My concern is for the constraint
` v_min^2 <= v_real[i]^2 + v_imag[i]^2 <= v_max^2`,
which should be categorized as two inequality constraints, one with upper bound and the other with lower bound. But as I showed in the previous post, it looks like this constraint is not considered for all buses since the numbers do not add up.

**Comment by ccoffrin** [comment]
I am not aware of any reason that the voltage bounds would not be posted.  The relevant constraint is here, https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/form/acr.jl#L4.

Instead of counting the number of constraints in Ipopt's output why not print the JuMP model created by PowerModels on some small networks to build an intuition for what constraints are generated?

**Comment by ksun46** [comment]
I tried to implement the ACR model and noticed this difference with PowerModels. Voltage bounds not being posted is my guess. I did looked into some small networks (14, 30), and both the model and IPOPT summary (the numbers add up) looked corrected. I can check some more instances. Thanks

**Comment by ksun46** [comment]
Any possibility that the [angle difference bound](https://github.com/lanl-ansi/PowerModels.jl/blob/e28644bf85232a5322adeeb847c0d18b7ff4f235/src/form/acr.jl#L113) is not added for all branches? Network 57 has 80 branches (all active) and 78 branches have this constraint. Thanks.

**Comment by ccoffrin** [comment]
In the case of parallel branches it will only be added on one of the
branches.

**Comment by ksun46** [comment]
I see. Thanks a lot!
