### ISSUE TITLE
Allow add_setpoint to post a subset of variables

### ISSUE THREAD

**Issue by noahrhodes** [lanl-ansi/PowerModels.jl#566]
i.e. provide a list of damaged generators to `add_setpoint_gen_status!(...)` and only add this subset of generator variable values.

This can prevent attempting to index a variable that may not exist for all ids.

**Comment by ccoffrin** [comment]
This should be resolved by the solution reporting changes in v0.15.

**Comment by ccoffrin** [comment]
This should be resolved by the solution reporting changes in v0.15.
