### ISSUE TITLE
JuMP v0.20 / MOI v0.9 Update

### ISSUE THREAD

**Issue by lschmelting** [lanl-ansi/PowerModels.jl#583]
Hello,

When are you planning on changing the dependencies on MathOptInterface to version v0.9.0? Is there much work involved? Is there any way the people interested in this change can help out? 

The root of the interest stems from this issue on the Ipopt.jl repo: JuliaOpt/Ipopt.jl#178, where at least 3 people showed interest in using Ipopts "wall clock time per iteration" feature. Ipopt requires v0.9.0 of MathOptInterface to use this.

Kind regards

**Comment by ccoffrin** [comment]
I always endeavor to keep PowerModels up to date with the latest version of all dependencies.

As for MOI v0.9, as I understand it, first JuMP needs to support this (v0.20, I believe?), then the Juniper solver can be updated, then PowerModels can updated.  Sound right @mlubin, @blegat?

If I had to guess on a time, probably the end of September.
