### ISSUE TITLE
Duals for AbstractWForms formulations

### ISSUE THREAD

**Issue by andrewrosemberg** [lanl-ansi/PowerModels.jl#591]
Following on the discussion on [discourse](https://discourse.julialang.org/t/power-balance-reference-in-powermodels-jl/27865) about power balance constraint reference in the "con" dictionary, I have forked and made the changes to the appropriate file : [shared.jl](https://github.com/lanl-ansi/PowerModels.jl/blob/52e39620093a80997ef2e1f9cb3996f5ce89def5/src/form/shared.jl#L58-L69) => [shared.jl](https://github.com/andrewrosemberg/PowerModels.jl/blob/69e8a0b1b885a9745bca4ba60961269df46e721c/src/form/shared.jl#L58-L69).

However, this was not enough to allow retrieving of the dual value of those constraints. I'm still getting a `result["solution"]["bus"]["1"]["lam_kcl_r"] = NaN` when solving with a SDPWRMForm or SOCWRConicForm formulation.

Does anyone have an idea of which other files and functions should I change to fix this?

**Comment by blegat** [comment]
Yes, that should work, which solver is used ? What is the `dual_status` ?
