### ISSUE TITLE
How to incorporate start-up & shut-down costs?

### ISSUE THREAD

**Issue by Misbahrani** [lanl-ansi/PowerModels.jl#596]
Hello,
I want to implement the start-up and shutdown costs of the generators. AS the operational cost estimation using quadratic fuel cost functions is easily done in Powermodels, I was wondering to expand the cost estimation,and want to incorporate startup costs, so at OPF the cheapest generators is turned ON first. Plus i want to incorporate ramp limits and start-up time. How to do that in powermodels framework?
Best regards,
Misbah Rani

**Comment by ccoffrin** [comment]
Hi Misbahrani

Incorporating a cost for starting or stopping a unit is fairly straightforward.  Have a look at the toy Unit Commitment example here, https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/prob/test.jl#L259.  The `variable_generation_indicator` function adds a variable called `:z_gen` to the model which is 0/1 based on if the generator is active or not.  Using this, you could re-write `objective_min_fuel_and_flow_cost` to include some additional costs for generation start/stop changes.

Adding ramping will be more complex.  To do multi-timepoint optimization PowerModels uses a feature called multi-network.  This lets you solve multiple versions of a network in a common optimization model.  This link provides an example of what that looks like and how storage constraints link over time, https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/prob/test.jl#L615.  To implement rapping you would need to link the generator variables (e.g. `:pg`, `:qg`) across the multiple networks in a meaningful way.

PS: for future refrence, https://discourse.julialang.org is a better place for discussions like this one.  This area is best for tracking known problems or feature requests for the package.

**Comment by Misbahrani** [comment]
Okay, thanks for guiding me through this, I really appreciate your help. I
will check the links.

**Comment by ccoffrin** [comment]
Great.  Can we close this issue (for now at least) and move the discussion to discourse?  Make sure to at mention me on discourse so that I see your post.
