### ISSUE TITLE
Line parameters for DC OPF and other lossless calculations

### ISSUE THREAD

**Issue by lroald** [lanl-ansi/PowerModels.jl#597]
I have a question about the calculation of line parameters for the DC models.

In PowerModels.calc_branch_y (https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/data.jl#L18), the calculation of g_ij and b_ij is done by calculating y_ij = g_ij+j*b_ij = 1/(r_ij+j*x_ij).

This is also used for calculating the line parameters for the DC OPF examples in PowerModelsAnnex.jl (https://github.com/lanl-ansi/PowerModelsAnnex.jl/blob/master/src/model/dc-opf.jl#L142 and https://github.com/lanl-ansi/PowerModelsAnnex.jl/blob/master/src/model/opf.jl#L659).

However, it seems to be standard convention for DC power flow calculations to calculate b_ij = 1/x_ij, as opposed to use the imag(1/(r_ij+j*x_ij), see for example section 3.17 in the matpower manual. 

This is of course not a problem if the user sets all the r values to zero before using calc_y_branch, but this is not done in the PowerModelsAnnex.jl example. I wanted to bring this as a question to PowerModels since I am not sure if things work in the same way when running DC OPF / DC power flow with PowerModels? Otherwise, this might be a question that belongs in PowerModelsAnnex.

**Comment by ccoffrin** [comment]
I am aware that Matpower uses the convention of `1/x` for calculating susceptance parameters in the DC power flow.  Back in 2011 I did a small survey of a few text books and papers and I did not find a particular standard for how to compute this parameter.  At that time I did a power flow study to see if there was a difference in accuracy for `1/x` or `-b`, the results suggested the two approaches lead to different power flows but accuracy is similar in both cases.

Given that both approaches seem to be comparable in accuracy, in PowerModels (and my other works), I chosen to standardize with `-b`.  The primary release is that this version has a nice interpretation as a first-order taylor expansion of the AC polar equations.  So I think it's a little more consistent in a framework that switches between DC and AC power flow.

Do you have a strong motivation to change the standard to `1/x`?

**Comment by lroald** [comment]
Yes, I see your point and I agree that it is more consistent to keep the same definition when switching between the two.
I guess my only counterargument would be that what you really assume when you say the line is lossless, is not that the admittance is zero, but that the resistance is zero... However, this is of course only an assumption that is applicable in systems where r is very small relative to x, and in that case the result is essentially the same. 

So I guess it is fair to leave it as it is :)

**Comment by rb004f** [comment]
We have a similar question/issues over in GasModels... there are multiple ways in the literature for computing resistance of a pipe (the analogue of suscpentance and conductance.... ultimately, the path we took there was to store the computed resistance value in the ref table that way a user can override that value if they have a different computation.  See https://github.com/lanl-ansi/GasModels.jl/blob/master/src/core/base.jl : 

```
for (idx,pipe) in ref[:pipe]
            ref[:w][idx] = calc_pipe_resistance_thorley(ref, pipe)
end
```

**Comment by ccoffrin** [comment]
Concerning both points, if one would like to study these kinds of model variants my recomend ation would be,
1. If possible just modify the input data.  In Line's example, the existing mathematical models general and can be re-used for the `1/x` case simply by setting `r=0`.
2. If that is not possible, the second choice would be to make new constraint names that encode which variant of the model you will use.  In that case data processing is done at the constraint template level.  The goal is that a user can see at the modeling level which version of the constraints they are using

**Comment by ccoffrin** [comment]
If all points are addressed can we close this issue?

**Comment by lroald** [comment]
For the power flow case, I agree with your first point - let users modify the data (and set r=0 if that is what they want). 

From my perspective, we can close this issue.

**Comment by ccoffrin** [comment]
Great.  Thanks!
