### ISSUE TITLE
Best Output Behavior of Bus Phase Angles, when the model has no such variable

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#6]
For example, in the SOC relaxation, should the output Bus Phase Angles absent, NaN, 0?

**Comment by rb004f** [comment]
Good question.  I have generally sent back what the model assumes about those variables. So, for the DC model I would send back voltage = 1 and reactive power = 0.  Not sure what that should mean for SOC... I think it would be safe to send back nothing?

**Comment by ccoffrin** [comment]
The convention I have been using thus far is that within a problem domain (say OPF), the there are no _optional_ data fields in the output format.  In the case of OPF all outputs must define a value for v, theta, p, and q.  The benefit is that codes that process these outputs don't need to know anything about the underlying model and don't need to do a lot of key-existence checking. 

Given that values are not optional, the general rule of thumb has been that if a model does not represent that particular data, the value is NaN ("undefined" would be better, but NaN is all we got...).  In the DC OPF case, all of the q values NaN.  The v values in DC OPF are a notable exception, the way I see v is that it is implicitly 1.0, and simply not represented in the formulation as a variable.  So in this case, we output 1.0 instead of NaN.

So now moving on to the relaxations, which do not have an explicit theta variable (e.g. SDP, SOC, DistFlow, ...),  the key question is, is their value of theta "undefined" (i.e. NaN), or one of these  implicitly special cases, like a voltage in the DC.

My current inclination is that theta is NaN in these models.  The reason is, if you try to re-derive the line flows with theta = 0 at all buses, the result would be incorrect.  And due to the "virtual phase shifter" property, on cyclic networks there is rarely an assignment of theta that is consistent with the values of the voltage variables in these models.

**Comment by ccoffrin** [comment]
Has been addressed by new solution reporting convention in PowerModels v0.15 and and solution post-processor feature.
