### ISSUE TITLE
The formulation of DCPLL model

### ISSUE THREAD

**Issue by shiftlin89** [lanl-ansi/PowerModels.jl#603]
Firstly,  Dr. ccoffrin, thanks for the wonderful work.
I tested different OPF models in PowerModels.jl and found that the DCPLL model is what I want. I read the paper referred, the manual on the website and try to trace the code to find its formulation. But I am new to Julia language, I only dig out the inequality constraints and still hard for the equality constraints. Also it seems that the model implemented in the code is different from that in the paper and no more document to introduce this. so it's appreciated that if the model of DCPLL implemented in PowerModels.jl can be provided or more information can be referred. thanks!

**Comment by ccoffrin** [comment]
Thanks!  Yes, the documentation should be improved in this regard.  In the meantime I would recomend looking at the the JuMP model in a small example to see exactly the formulation that is generated.  Something along these lines should work,
```
using JuMP; using PowerModels; using Ipopt

m = Model()
result = run_opf("case5.m", DCPLLPowerModel, with_optimizer(Ipopt.Optimizer), jump_model=m)
println(m)
```

**Comment by shiftlin89** [comment]
OK, thanks!
I have figured out this model
The result of this model is amazing close to that of ACOPF

**Comment by ccoffrin** [comment]
Glad to hear it!

**Comment by ccoffrin** [comment]
@shiftlin89, have you also tried the LPACC model?  It is similar to DCPLL in terms of active power but also includes an approximation of voltages and reactive power.

**Comment by shiftlin89** [comment]
The result of LPACC model is not close to the result of AC exact model in terms of active power compared with DCPLL model. The time of LPACC is also longer.
Though the LPACC model can provide the reactive power approximation result but for some generators , their reactive power is not close to the AC model .

This is the result of case 57-bus system
objs(ACOPF DC DCPLL LPACC):
41737.786729608546   41006.736942055555   41688.802753183845   41418.01317480326

time(ACOPF DC DCPLL LPACC):
0.09095045   0.015330312   0.042965777   0.14046092

active power(ACOPF DC DCPLL LPACC)
4    0.7286264292403812   0.819313277350866   0.7228780370285702   0.749460820454859
1    1.426262960389878   1.3946094928618462   1.4269200386182745   1.4316135887097683
5    4.598048300250407   4.868691003453284   4.582590802287981   4.613828446983767
2    0.8779098557067828   0.8193132775805083   0.8804209161402254   0.9088367858438053
6    0.976344672444417   0.8193132772252484   0.9801539948810376   0.9031406632619643
7    3.615220335749039   3.3539871363509275   3.6166942947220657   3.5449047264709628
3    0.45070948227709856   0.43277253517731956   0.4511022491316682   0.4478277074615703
reactive power (ACOPF DC DCPLL LPACC)
4    0.07763267364479452   NaN   NaN   0.24999894147972468
1    0.44585219447488295   NaN   NaN   1.9999992283494685
5    0.8719895489554148   NaN   NaN   1.418386627080869
2    0.4999997802334505   NaN   NaN   0.4999997999390734
6    0.08999986334323953   NaN   NaN   0.08999836557215359
7    0.4325722497412713   NaN   NaN   -1.0461982793953388
3    0.28753603673728917   NaN   NaN   0.14572241730839605

**Comment by ccoffrin** [comment]
It is surely the case that estimating reactive power from a cold-start is much more difficult than active power, so I am not surprised that the LPACC model is inaccurate in that case.  As for the difference with DCPLL, my experience has been that in unconstrained cases DCPLL can be very accurate, once line limits start to be important then it is optimistic about the high loaded lines.

In any case, this is the primary motivation of PowerModels, to make it easy to switch between power flow formulations based on the level of performance and accuracy is needed for specific cases / applications.  It's great to hear that you find DCPLL useful, this should be a suitable refrence for [that model](https://ieeexplore.ieee.org/abstract/document/6345342).
