### ISSUE TITLE
Solution builder fails on components with status=1 and their bus_status = 4

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/PowerModels.jl#606]
Solution builder fails on components with status=1 (generators, branch, loads) and the bus they are connected to has bus_status = 4.  The build_ref eliminates these components so that variables are not created.  However, the solution builder looks for these non existent variables if their status = 1

A temporary fix is to run ```propagate_topology_status!``` which makes all statuses consistent.

**Comment by ccoffrin** [comment]
I believe this has been addressed by the new solution building infrastructure that was added in PowerModels v0.15.
