### ISSUE TITLE
Error with `(v1.2) pkg> test PowerModels`

### ISSUE THREAD

**Issue by bcdandurand** [lanl-ansi/PowerModels.jl#610]
I'm installing PowerModels. After running

`(v1.2) pkg> add PowerModels`

successfully, then I try

`(v1.2) pkg> test PowerModels`

I get the following output then error:

>  Testing PowerModels
>  Resolving package versions...
>  Installed Cbc ───── v0.6.4
>  Installed Juniper ─ v0.5.2
>   Building Cbc → `~/.julia/packages/Cbc/8nwnT/deps/build.log`
>     Status `/tmp/jl_mNvZfI/Manifest.toml`
>   [6e4b80f9] BenchmarkTools v0.4.3
>   [9e28174c] BinDeps v0.8.10
>   [b99e7846] BinaryProvider v0.5.6
>   [49dc2e85] Calculus v0.5.0
>   [9961bab8] Cbc v0.6.4
>   [bbf7d656] CommonSubexpressions v0.2.0
>   [34da2185] Compat v2.2.0
>   [864edb3b] DataStructures v0.17.2
>   [163ba53b] DiffResults v0.0.4
>   [b552c78f] DiffRules v0.0.10
>   [8f5d6c58] EzXML v0.9.4
>   [f6369f11] ForwardDiff v0.10.3
>   [2030c09a] InfrastructureModels v0.3.2
>   [b6b21f68] Ipopt v0.6.0
>   [682c06a0] JSON v0.21.0
>   [4076af6c] JuMP v0.20.0
>   [2ddba703] Juniper v0.5.2
>   [b8f27783] MathOptInterface v0.9.4
>   [fdba3010] MathProgBase v0.7.7
>   [f28f55f0] Memento v0.12.1
>   [78c3b35d] Mocking v0.7.0
>   [77ba4419] NaNMath v0.3.2
>   [bac558e1] OrderedCollections v1.1.0
>   [69de0a69] Parsers v0.3.7
>   [c36e90e8] PowerModels v0.13.0
>   [c946c3f1] SCS v0.6.1
>   [276daf66] SpecialFunctions v0.7.2
>   [90137ffa] StaticArrays v0.11.0
>   [cea106d9] Syslogs v0.3.0
>   [f269a46b] TimeZones v0.10.2
>   [30578b45] URIParser v0.4.0
>   [2a0f44e3] Base64  [`@stdlib/Base64`]
>   [ade2ca70] Dates  [`@stdlib/Dates`]
>   [8bb1440f] DelimitedFiles  [`@stdlib/DelimitedFiles`]
>   [8ba89e20] Distributed  [`@stdlib/Distributed`]
>   [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
>   [76f85450] LibGit2  [`@stdlib/LibGit2`]
>   [8f399da3] Libdl  [`@stdlib/Libdl`]
>   [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
>   [56ddb016] Logging  [`@stdlib/Logging`]
>   [d6f4376e] Markdown  [`@stdlib/Markdown`]
>   [a63ad114] Mmap  [`@stdlib/Mmap`]
>   [44cfe95a] Pkg  [`@stdlib/Pkg`]
>   [de0858da] Printf  [`@stdlib/Printf`]
>   [3fa0cd96] REPL  [`@stdlib/REPL`]
>   [9a3f8284] Random  [`@stdlib/Random`]
>   [ea8e919c] SHA  [`@stdlib/SHA`]
>   [9e88b42a] Serialization  [`@stdlib/Serialization`]
>   [1a1011a3] SharedArrays  [`@stdlib/SharedArrays`]
>   [6462fe0b] Sockets  [`@stdlib/Sockets`]
>   [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
>   [10745b16] Statistics  [`@stdlib/Statistics`]
>   [8dfed614] Test  [`@stdlib/Test`]
>   [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
>   [4ec0a83e] Unicode  [`@stdlib/Unicode`]
> 
> ******************************************************************************
> This program contains Ipopt, a library for large-scale nonlinear optimization.
>  Ipopt is released as open source code under the Eclipse Public License (EPL).
>          For more information visit http://projects.coin-or.org/Ipopt
> ******************************************************************************
> 
> Intel MKL FATAL ERROR: Cannot load libmkl_avx512.so or libmkl_def.so.
> ERROR: Package PowerModels errored during testing

Also, I have the login profile run `soft add +mkl-19-u2` for the use of the Intel Math Kernel Library 19 update 2

**Comment by bcdandurand** [comment]
We think this is an issue with my custom configuration of Ipopt. `test Ipopt` has the same error.

**Comment by ccoffrin** [comment]
Ok, glad to hear you sorted it out.
