### ISSUE TITLE
Writing warnings to stderr

### ISSUE THREAD

**Issue by bcdandurand** [lanl-ansi/PowerModels.jl#618]
I found that warnings such as

> [warn | PowerModels]: this code only supports angmin values in -90 deg. to 90 deg., tightening the value on branch 19 from -360.0 to -60.0 deg.

are written to standard output. Would it be possible to have them written to standard error in the next release? Thank you.

**Comment by ccoffrin** [comment]
The Memento logging system can be used to control the level of output.  A simple solution is to call `PowerModels.silence()`

**Comment by ccoffrin** [comment]
@bcdandurand, shall we close this issue?

**Comment by bcdandurand** [comment]
Yes, you may close this issue. Thank you.
