### ISSUE TITLE
current limits vs apparent power limits

### ISSUE THREAD

**Issue by frederikgeth** [lanl-ansi/PowerModels.jl#625]
The apparent power limit functions are separate for to and from side:
- `constraint_thermal_limit_from`
- `constraint_thermal_limit_to`

Conversely, for the current magnitude, the limits is only enforced on the from side through `constraint_current_limit` 

I'm in favor of splitting `constraint_current_limit`  into `constraint_current_limit_to` and `constraint_current_limit_from`. What are your thoughts?

**Comment by ccoffrin** [comment]
Agreed, PR is welcome, but I would recomend that we start a `pms-v14` branch for breaking features (like this one).  Note, you have write access on this repo so you can make feature branches directly.

**Comment by frederikgeth** [comment]
Great, I'll get on this soon (likely after #622).

**Comment by friederikemeier** [comment]
I had the same idea recently. I would also appreciate this feature! Let me know if I can help.

**Comment by ccoffrin** [comment]
A PR with the change would surely be welcome but this will need to be added to the next breaking release (v0.18 right now).  I may be able to get to it in the next couple of weeks.

**Comment by friederikemeier** [comment]
Congrats on closing this issue. I tried to fix it in 2020 but didn't succeed and then moved on with my research in other directions... However, it feels like closure to me, too!
