### ISSUE TITLE
Missing branch rate_a data

### ISSUE THREAD

**Issue by KSepetanc** [lanl-ansi/PowerModels.jl#626]
I noticed that only on the network `pglib_opf_case10000_tamu.m` there are cases without branch rate_a data (and its `sad` and `api` versions).

Data version: 19.05 pglib-opf.
PowerModels: 0.13.0 (current)

I think this is a bug since as I think it had worked before in previous version of PowerModels.

Recreate error:

`url=".\\data\\typ\\pglib_opf_case10000_tamu.m"`
`network_data = PowerModels.parse_file(url)`
`data=PowerModels.build_ref(network_data)[:nw][0]`

`[data[:branch][l]["rate_a"] for l in keys(data[:branch])]`

Error:

ERROR: KeyError: key "rate_a" not found
Stacktrace:
 [1] getindex(::Dict{String,Any}, ::String) at .\dict.jl:477
 [2] (::getfield(Main, Symbol("##6215#6216")))(::Int64) at .\none:0
 [3] collect_to!(::Array{Float64,1}, ::Base.Generator{Base.KeySet{Int64,Dict{Int64,Any}},getfield(Main, Symbol("##6215#6216"))}, ::Int64, ::Int64) at .\generator.jl:47
 [4] collect_to_with_first!(::Array{Float64,1}, ::Float64, ::Base.Generator{Base.KeySet{Int64,Dict{Int64,Any}},getfield(Main, Symbol("##6215#6216"))}, ::Int64) at .\array.jl:630
 [5] collect(::Base.Generator{Base.KeySet{Int64,Dict{Int64,Any}},getfield(Main, Symbol("##6215#6216"))}) at .\array.jl:611
 [6] top-level scope at none:0

**Comment by ccoffrin** [comment]
As of v0.13 PowerModels now supports optional flow limits, see https://github.com/lanl-ansi/PowerModels.jl/pull/581 for details.   Now when cases like `pglib_opf_case10000_tamu.m` specify `rate_a` as 0, no rating is added to the power models data model and this constraint is omitted from the OPF optimization model.

If you would like to add a value for every line in the network (the pre-v0.13 semantics) you can use the `calc_thermal_limits!(data)` function to add resonable limits on all branches.

**Comment by KSepetanc** [comment]
I need it as intended by PowerModels since I am using it as a benchmark (so no power limit).

How can I check if there is data `rate_a` value without error?
I am exporting everything to excel to use it in gams.

I used the following code to get a Vector which I write to Excel using XLSX package.
`Slinemax = Vector()
        push!(Slinemax, ["l$(l)" for l in keys(data[:branch])])
        push!(Slinemax, [data[:branch][l]["rate_a"] for l in keys(data[:branch])])`

**Comment by ccoffrin** [comment]
`haskey` will let you check if a branch has `"rate_a"` defined and `get` can let you specify a default value when a key is not defined.

For example, this code,
```
push!(Smax, [data[:branch][l]["rate_a"] for l in keys(data[:branch])])
```
could now be re-written like so,
```
push!(Smax, [haskey(branch, "rate_a") ? branch["rate_a"] : 0.0 for (l,branch) in data[:branch]])
```
or
```
push!(Smax, [get(branch, "rate_a", 0.0) for (l,branch) in data[:branch]])
```

**Comment by KSepetanc** [comment]
Thank You for the help!

My problem has been solved and answered, so I will close this issue.

**Comment by ccoffrin** [comment]
Glad to hear it!
