### ISSUE TITLE
Giving variable bounds of -Inf, Inf

### ISSUE THREAD

**Issue by bcdandurand** [lanl-ansi/PowerModels.jl#630]
We encountered an issue where the variable bounds for the line flow variables are calculated as `-Inf` for the lower bound and `Inf` for the upper bound. Rather than creating these variables as free, the code sequence in core/variable.jl sets these bounds to their infinity values. For example

```
function variable_active_branch_flow(pm::AbstractPowerModel; nw::Int=pm.cnw, cnd::Int=pm.ccnd, bounded = true)
    if bounded
        flow_lb, flow_ub = ref_calc_branch_flow_bounds(ref(pm, nw, :branch), ref(pm, nw, :bus), cnd)

        p = var(pm, nw, cnd)[:p] = JuMP.@variable(pm.model,
            [(l,i,j) in ref(pm, nw, :arcs)], base_name="$(nw)_$(cnd)_p",
            lower_bound = flow_lb[l],
            upper_bound = flow_ub[l],
            start = comp_start_value(ref(pm, nw, :branch, l), "p_start", cnd)
        )
    else
        p = var(pm, nw, cnd)[:p] = JuMP.@variable(pm.model,
            [(l,i,j) in ref(pm, nw, :arcs)], base_name="$(nw)_$(cnd)_p",
            start = comp_start_value(ref(pm, nw, :branch, l), "p_start", cnd)
        )
    end
...
end
```
the `flow_lb[l]` and `flow_ub[l]` values can take values `-Inf` and `Inf`, respectively, and this causes errors for solvers like Mosek. 

We are able to fix this with code to delete these bounds whenever `lower_bound(p[l])==-Inf` and `upper_bound(p[l])==Inf`, for example. 

I only bring this issue up to request that this issue be addressed in future releases of PowerModels.jl. Thank you.

**Comment by ccoffrin** [comment]
Thanks for bringing this to my attention, it is an interesting point I had not considered.  This might indicate that there is an issue with inconsistencies across solver interfaces.  Can you provide a small working example of a JuMP model with `Inf` variable bounds that causes an issue with Mosek?

**Comment by bcdandurand** [comment]
```
using JuMP,Mosek,MosekTools

m = Model(with_optimizer(Mosek.Optimizer,MSK_IPAR_LOG=0,MSK_IPAR_NUM_THREADS=4))

@variable(m, x, lower_bound=0)
@variable(m, y, lower_bound=0)
#@variable(m, z)  ### Coding this in and coding out the next line will have successful termination
@variable(m, z, lower_bound=-Inf, upper_bound=Inf)  ### This is the source of the error
@constraint(m, [x+1,y+1,z] in SecondOrderCone())
@objective(m, Min, z)

JuMP.optimize!(m)
status=JuMP.termination_status(m)
println("The optimal value should be -1 and it is: ",JuMP.objective_value(m))
```

**Comment by ccoffrin** [comment]
@blegat what's your two cents on this?

**Comment by blegat** [comment]
We should indeed improve consistency across solvers on whether infinite values are allowed in bounds.
I would unallow it, in fact it will probably also fails with CSDP, SDPA, SDPT3 and SDPNAL as for `x >= -Inf` they will create a nonnegative variable `y` and substitute `x` by `y - Inf` which will not work.

**Comment by ccoffrin** [comment]
@blegat is there a default value I can pass to `@variable( ... lower_bound=` that will have the same effect as not giving a value to `lower_bound`?

**Comment by blegat** [comment]
Looking at:
https://github.com/JuliaOpt/JuMP.jl/blob/326017cd81b365e144ff8dfd8f1b92cf69ba65b5/src/variables.jl#L54-L57
It seems `lower_bound=NaN` should be equivalent to not giving the keyword argument.

**Comment by ccoffrin** [comment]
@blegat I gave this a try with the following program,
```
using JuMP
using Cbc
using Gurobi
using Ipopt

m = Model()

@variable(m, x >= 1, upper_bound = NaN)
#@variable(m, x >= 1.23, upper_bound = 10) # all solvers work
#@variable(m, x >= 1.23, upper_bound = Inf) # all solvers work

@objective(m, Min, x)

#optimize!(m, with_optimizer(Ipopt.Optimizer)) # MOI_wrapper breaks
#optimize!(m, with_optimizer(Cbc.Optimizer)) # solver terminates with "linear relaxation infeasible"
#optimize!(m, with_optimizer(Gurobi.Optimizer)) # c interface throws error

value(x)
```
Thoughts?

dev branch, https://github.com/lanl-ansi/PowerModels.jl/tree/var-bounds

**Comment by ccoffrin** [comment]
@bcdandurand, can you test the `var-bounds` branch and confirm that it resolves your issue?

**Comment by bcdandurand** [comment]
OK. I need to learn how to switch to this branch in my Julia installation.
I'm not sure what to do yet.

**Comment by ccoffrin** [comment]
from inside the package manager this should do the trick `] add PowerModels#var-bounds`

**Comment by bcdandurand** [comment]
After doing as instructed from the package manager, I still get the Mosek error:

> MOSEK error 1391: The upper bound specified is not a number (nan).
> ERROR: LoadError: MosekError(1391, "The upper bound specified is not a number (nan).")

I use the following routine as a hack around this problem, if this helps:

```
function remove_infinity_bnds(pm::AbstractPowerModel; nw::Int=pm.cnw, cnd::Int=pm.ccnd)
    p = var(pm, nw, cnd, :p)
    q = var(pm, nw, cnd, :q)
    for l in ref(pm,nw, :arcs)
      if lower_bound(p[l])==-Inf
        delete_lower_bound(p[l])
      end
      if lower_bound(q[l])==-Inf
        delete_lower_bound(q[l])
      end
      if upper_bound(p[l])==Inf
        delete_upper_bound(p[l])
      end
      if upper_bound(q[l])==Inf
        delete_upper_bound(q[l])
      end
    end
end

```

**Comment by bcdandurand** [comment]
Actually, with the new branch, I did need to modify the above script to test `has_lower_bound()` and `has_upper_bound()`. Otherwise, there was still need to test +-Inf bounds.

```
function remove_infinity_bnds(pm::AbstractPowerModel; nw::Int=pm.cnw, cnd::Int=pm.ccnd)
    p = var(pm, nw, cnd, :p)
    q = var(pm, nw, cnd, :q)
    for l in ref(pm,nw, :arcs)
     if has_lower_bound(p[l])
      if lower_bound(p[l])==-Inf 
        delete_lower_bound(p[l])
      end
     end
     if has_lower_bound(q[l])
      if lower_bound(q[l])==-Inf 
        delete_lower_bound(q[l])
      end
     end
     if has_upper_bound(p[l])
      if upper_bound(p[l])==Inf 
        delete_upper_bound(p[l])
      end
     end
     if has_upper_bound(q[l])
      if upper_bound(q[l])==Inf 
        delete_upper_bound(q[l])
      end
     end
    end
end
```

**Comment by bcdandurand** [comment]
In variable.jl, there is the code segment

```
if flow_ub[l] != -Inf
                JuMP.set_upper_bound(p[arc], flow_ub[l])
end
```

that should be changed to

```
if flow_ub[l] != Inf
                JuMP.set_upper_bound(p[arc], flow_ub[l])
end
```
where `-Inf` is changed to `Inf`. Let me know when this change has been made and I'll test again.

**Comment by ccoffrin** [comment]
Ok thanks.  I am going to add a test for this specific case this before I merge so that we don't have a regression in the future.
