### ISSUE TITLE
Incorrect conversion between current and power rating

### ISSUE THREAD

**Issue by peraaslid** [lanl-ansi/PowerModels.jl#631]
The conversion from current to power rating seems to be wrong. Current rating is divided with voltage instead of multiplied with.

https://github.com/lanl-ansi/PowerModels.jl/blob/90d770793b73d1f5da6cc1641d174cab262eb79b/src/core/ref.jl#L86-L87

**Comment by ccoffrin** [comment]
Yup, that looks like a bug.  Will fix it soon.

**Comment by ccoffrin** [comment]
Thanks for the tip @peraaslid!
