### ISSUE TITLE
Non-positive definite error with cholesky in chordal extension

### ISSUE THREAD

**Issue by bcdandurand** [lanl-ansi/PowerModels.jl#641]
If I understand correctly, the W in the following segment of code starting at 

> src/form/wrm.jl#L301

constructs a Hermitian matrix `W` that is the signless Laplacian associated with the network topology graph. Subsequently in the code, Cholesky factorization is performed on `W`, i.e., `F = cholesky(W)`. However, when (and only when) the underlying network topology graph is bipartite (aside from any isolated vertices), then `W` has a zero eigenvalue, causing `cholesky(W)` to fail. This happens, for example with the IEEE case 9 topology when calling `variable_voltage(pm::AbstractSparseSDPWRMModel; nw::Int=pm.cnw, cnd::Int=pm.ccnd, bounded=true)`.

The possibility that `W` is merely positive semidefinite with zero eigenvalue needs to be addressed in the construction of chordal extensions. Thank you. Let me know if I can answer any questions.

```
function _chordal_extension(pm::AbstractPowerModel, nw::Int=pm.cnw)
    adj, lookup_index = _adjacency_matrix(pm, nw)
    nb = size(adj, 1)
    diag_el = sum(adj, dims=1)[:]
    W = Hermitian(adj + spdiagm(0 => diag_el))

    F = cholesky(W)
    L = sparse(F.L)
    p = F.p
    q = invperm(p)

    Rchol = L - spdiagm(0 => diag(L))
    f_idx, t_idx, V = findnz(Rchol)
    cadj = sparse([f_idx;t_idx], [t_idx;f_idx], trues(2*length(f_idx)), nb, nb)
    cadj = cadj[q, q] # revert to original bus ordering (invert cholfact permutation)
    return cadj, lookup_index, p
end
```

**Comment by bcdandurand** [comment]
One idea, assuming my understanding that `W` is the signless Laplacian, is to write `W=JJ^*` where `J` is the vertex edge incidence matrix with rows corresponding to bus indices. Then apply QR decomposition to `J^*`, writing `J^*=QR`. Then `W=R^* R`, so that `L=R^*` is lower triangular.

**Comment by bcdandurand** [comment]
But then, equation (23) in 

> D. K. Molzahn, J. T. Holzer, B. C. Lesieutre and C. L. DeMarco, "Implementation of a Large-Scale Optimal Power Flow Solver Based on Semidefinite Programming," in IEEE Transactions on Power Systems, vol. 28, no. 4, pp. 3987-3998, Nov. 2013.

suggests that we compute `W = Laplacian + Identity` as an alternative, which in code would be something like
`W = Hermitian(-adj + spdiagm(0 => diag_el)) + eye(nb)`
This computation of W would be positive definite, and the sparsity pattern of its Cholesky factorization would be the same as the sparsity pattern of the Cholesky factorization of `|im(Y)|`, the matrix having the absolute values of the imaginary components of the admittance matrix `Y`.

**Comment by ccoffrin** [comment]
The use of `cholesky` for building the sparse SDP constraints was done at the recommendation of Dan Molzahn.  As I understand it, this is the approach he is using in his current matlab implementations of SDP relaxations.  

I have noticed in some cases the call to `cholesky` fails.  In the long run, I would like to replace it with a graph-based cordal extension for building a sparse SDP.  This is not a high priority for me at the moment, but contributions in that direction would be welcome.

**Comment by bcdandurand** [comment]
In the short run (that is putting aside graph-based chordal extension for now), it may be adequate to replace
`W = Hermitian(adj + spdiagm(0 => diag_el))`
with the minor code edits needed to instead set
`W = Hermitian(-adj + spdiagm(0 => diag_el)) + eye(nb)`
This is how my local version of `wrm.jl` is currently modified and the problem seems to be fixed. I'll double-check with Dan Molzahn that this modification is sound and get back....

**Comment by ccoffrin** [comment]
Sounds great, thanks!
