### ISSUE TITLE
_make_multiconductor! still has vector shunts instead of square matrices

### ISSUE THREAD

**Issue by frederikgeth** [lanl-ansi/PowerModels.jl#648]
_make_multiconductor! still has vector shunts, whereas PowerModelsDistribution switched it data model to matrix shunts. I reckon this should be brought into sync with the actual PMD datamodel?

**Comment by ccoffrin** [comment]
Agreed, if you can make a PR to `pms-v14-rc` I cam make sure to get it in the next breaking release.

**Comment by ccoffrin** [comment]
@frederikgeth, I am thinking we can close with v0.15 as the feature will only be needed in PMD, correct?

**Comment by frederikgeth** [comment]
correct
