### ISSUE TITLE
Math Rendering in Docs

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#667]
There seems to be an issue rendering the mathematical models in the latest version of Documenter.jl.

@frederikgeth, at your convenience can you take a look?

**Comment by ccoffrin** [comment]
This is not blocking for the v0.15 tag.

**Comment by guilhermebodin** [comment]
This is usually soved by this line on make.jl ` format   = Documenter.HTML(mathengine = Documenter.MathJax()),` In PowerModels it would be `format = Documenter.HTML(analytics = "UA-367975-10", mathengine = Documenter.MathJax())`

**Comment by ccoffrin** [comment]
That seems to have resolved the issue.  Thanks @guilhermebodin!
