### ISSUE TITLE
Using an out-of-scope variable - ref extensions

### ISSUE THREAD

**Issue by kaarthiksundar** [lanl-ansi/PowerModels.jl#668]
https://github.com/lanl-ansi/PowerModels.jl/blob/d1ab450bb68fdbdc687564be3651c5ddf420ab72/src/core/base.jl#L244

@ccoffrin what is ``pm`` in the line ``ref_ext(pm)``. It is not in scope. But I guess the tests does not capture this.

**Comment by ccoffrin** [comment]
Good catch!  The `ref_ext` does not make sense outside of `instantiate_model` call, so I think I would just remove that functionality from this method.

**Comment by kaarthiksundar** [comment]
Actually, it is a nice feature and does make sense. But it is just that the input to the ``ref_ext`` functions should be the ``ref`` itself in addition to the ``data``. I see why you would pass on ``AbstractPowerModel`` itself since it contains both. Let me know what you think.

**Comment by ccoffrin** [comment]
Good point, if you like we can change the API of the `ref_ext` to those two arguments instead of the `AbstractPowerModel`.  Can you tell me a little more about your use case?  At the moment I am only using this feature for backward compatibility with some code that was pre-`ref_ext`.

**Comment by kaarthiksundar** [comment]
Consider this - I have some new expansion planning model that I want to build from scratch (stand-anlone: think PowerModelsAnnex type) with data having additional fields. I would use the plain build_ref and add additional fields that include the expansion options into ref according to my need.

**Comment by ccoffrin** [comment]
Fair point, but why do you want to add these options via the `ref_extensions` call, instead of after you get a hold of the `ref` object?  Because you want to use some `ref_extensions` that are already part of PowerModels?

**Comment by kaarthiksundar** [comment]
Yes, but my use case was for GasModels. Basically I am reading in the static data using ``parse_file()``, then adding a bunch of additional fields to the data dictionary using a ``prep_transient_data(data::Dict{String,Any})`` and then building the ref. Ideally the basic ``build_ref`` will take care of all the fields that are need for the static data and my extension would add the additional fields to the ``ref``. Either way, the only things that the ``ref_ext`` would require is the ref and the data. It is independent of the model.

**Comment by ccoffrin** [comment]
Sounds good.  I am open to making this API change the new standard approach.

**Comment by kaarthiksundar** [comment]
Great, thanks

**Comment by kaarthiksundar** [comment]
@ccoffrin How do you make changes to the data if you have additional fields. For instance lets say you read in additional fields from the matpower extension format. Where does the code for making every additional field go?

**Comment by ccoffrin** [comment]
so far every set of data extensions have been associated with a specific problem definition.  A `ref_extention` is defined for that specific problem that deals with the additional fields.  For example, https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/prob/tnep.jl#L70.

**Comment by ccoffrin** [comment]
closed in v0.16
