### ISSUE TITLE
Is `multiconductor` keyword argument still needed in `instantiate_model`?

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/PowerModels.jl#670]
Without the `multiconductor` keyword argument, our calls to run_model can be much cleaner in PowerModelsDistribution. I only see that it throws an error if the keyword argument is inconsistent with the state of the data, but no where else do I see it used.

Related, is the `multinetwork` keyword argument still needed?

**Comment by ccoffrin** [comment]
Both of these are just about making things simpler for users by giving informative error messages.  The formulation one is using should be consistent with these features.

I am not inclined to get rid of them, but let's discuss the details in person.

**Comment by ccoffrin** [comment]
I wanted to double check if the generic build changes from IM v0.4.3 (which will be active in PowerModels v0.16) have addressed this issue or not?  The new version can be viewed here, https://github.com/lanl-ansi/PowerModels.jl/blob/rc-v0.16/src/core/base.jl#L31

**Comment by ccoffrin** [comment]
This may also answer this question, https://github.com/lanl-ansi/PowerModelsDistribution.jl/pull/258

**Comment by ccoffrin** [comment]
@pseudocubic, with https://github.com/lanl-ansi/PowerModelsDistribution.jl/pull/258 closed would you consider this issue resolved?
