### ISSUE TITLE
Wrong q_min limit in storage testcase

### ISSUE THREAD

**Issue by peraaslid** [lanl-ansi/PowerModels.jl#672]
Storage qmin is 110 while thermal rating is 100. Assume qmin should have been -110. It is causing infeasable problem.
https://github.com/lanl-ansi/PowerModels.jl/blob/67800808bf364028ec478e725cbcfaaee6be005c/test/data/matpower/case5_uc_strg.m#L57

**Comment by ccoffrin** [comment]
If I recall correctly. the goal here is to test a unit commitment storage formulation.  The trivial infeasibility was introduced to check that the commitment variable would be set to zero and hence remove the storage unit from the network.

**Comment by peraaslid** [comment]
Ok, makes sense. Thanks for the clarification.

**Comment by ccoffrin** [comment]
Sure thing, any time.
