### ISSUE TITLE
Break propagate_topology_status! into seperate functions

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/PowerModels.jl#677]
Consider breaking propagate_topology_status! into separate functions. The propagate_topology_status! function could be refactored to call each separate function, but aspects of that function could be independently executed.  We came across a use case where parts of the propagate_topology_status! are needed and some result incorrect behavior.

Specifically, consider the use case which includes damage to buses and optimization variables to repair or harden those buses. If a damaged bus gets aggregated because it has no load or generation, then this will result in a formulation which essentially hardens/repairs those buses for "free".  However, the rest of the propagate_topology status would still be good to use.

**Comment by ccoffrin** [comment]
Good point.  I agree the removal of sections without load or generation is a functionality that should be added on top of the typical status propagation.

In the specific case you mention, you might want to have a look at the `damage` parameter in PowerModelsRestoration.  In that case it is more explicit what is turned off (i.e. status=0) and what is damaged and should be considered for repair (i.e. damaged=1).
