### ISSUE TITLE
Wrong name for reactive power balance constraint 

### ISSUE THREAD

**Issue by martincornejo** [lanl-ansi/PowerModels.jl#678]
In the w-theta formulation, the reactive power balance constraint has been named wrong. It is written ``cstr_p`` instead of ``cstr_q``.

https://github.com/lanl-ansi/PowerModels.jl/blob/bd1f54949076b08a999c08efa66e4e0d77ec3396/src/form/act.jl#L57

**Comment by ccoffrin** [comment]
Fixed on master.  Thanks for the report!
