### ISSUE TITLE
Support generator impedance fields in PTI RAW33 parser

### ISSUE THREAD

**Issue by bluejuniper** [lanl-ansi/PowerModels.jl#685]
PTI RAW33 includes fields for the generator transient impedance and optionally the step-up transformer impedance: ZR, ZX, RT, XT. These fields are useful for fault studies.  Propose supporting them in the RAW parser so a fault study formulation can make use of them.

**Comment by ccoffrin** [comment]
did you try the `import_all` parameter?  It should import these values for you.

**Comment by bluejuniper** [comment]
now I see them, thanks Carleton

**Comment by ccoffrin** [comment]
Great! Shall we close issue?

**Comment by bluejuniper** [comment]
yes, that's fine
