### ISSUE TITLE
JSON Object Types

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#7]
By default JSON.parse returns Dict{UTF8String, Any} and we typically use Dict{AbstractString, Any}.

1) Figure out why a function of Dict{AbstractString, Any} cannot accpt an argument of Dict{UTF8String, Any}.

2) Migrate code to a robust solution, no types?

3) remove special type cases from JSON.parse() calls

**Comment by mlubin** [comment]
All of the string stuff is changing in 0.5

**Comment by mlubin** [comment]
(By the way, this would be a good time to test since 0.5 is in the final RC stages.)
