### ISSUE TITLE
Modeling Layer Naming Convention

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#701]
I propose to adopt the following naming convention to help us better organize the modeling layer of PowerModels.  I will leave this topic open for discussion for at least 7 days.  If you would prefer a change to the modeling layer names, now is a good time to speak up (looking at @frederikgeth).  Adoption of this convention will be strongly encourage by downstream packages in the interest of consistency.

The proposed update is planned for the PowerModels v0.17 release via PR https://github.com/lanl-ansi/PowerModels.jl/pull/700, which proposes the name changes below.

Let the bike shedding begin!  @pseudocubic, @sanderclaeys, @rb004f, @hakanergun, @noahrhodes, @bluejuniper

The proposed general form:
```
<jump macro id>_<comp short name>_<quantity name>(_real|_imaginary|_magnitude|_angle|_factor)(_fr|_to)(_sqr)(_on_off)
```
in the interest of intuitive names for users, the following special cases are also acceptable,
- `_power_real` -(can be replaced with)-> `_active`
- `_power_imaginary` -(can be replaced with)-> `_reactive`

Variable Definition Name Changes
```
variable_active_branch_flow -> variable_branch_power_real
variable_active_branch_flow_ne -> variable_ne_branch_power_real
variable_active_dcline_flow -> variable_dcline_power_real
variable_active_generation -> variable_gen_power_real
variable_active_generation_on_off -> variable_gen_power_real_on_off
variable_active_storage -> variable_storage_power_real
variable_active_storage_on_off -> variable_storage_power_real_on_off
variable_active_switch_flow -> variable_switch_power_real

variable_branch_flow -> variable_branch_power
variable_branch_flow_ne -> variable_ne_branch_power
variable_branch_ne -> variable_ne_branch_indicator
variable_bus_voltage -> variable_bus_voltage_magnitude

variable_cosine -> variable_buspair_cosine
variable_cosine_on_off -> variable_branch_cosine_on_off
variable_current_magnitude_sqr -> variable_buspair_current_magnitude_sqr
variable_current_magnitude_sqr_on_off -> variable_branch_current_magnitude_sqr_on_off
variable_current_storage -> variable_storage_current

variable_dcline -> variable_dcline_current
variable_dcline_flow -> variable_dcline_power
variable_demand_factor -> variable_load_power_factor

variable_gen -> variable_gen_current
variable_generation -> variable_gen_power
variable_generation_indicator -> variable_gen_indicator
variable_generation_on_off -> variable_gen_power_on_off

variable_reactive_branch_flow -> variable_branch_power_imaginary
variable_reactive_branch_flow_ne -> variable_ne_branch_power_imaginary
variable_reactive_dcline_flow -> variable_dcline_power_imaginary
variable_reactive_generation -> variable_gen_power_imaginary
variable_reactive_generation_on_off -> variable_gen_power_imaginary_on_off
variable_reactive_storage -> variable_storage_power_imaginary
variable_reactive_storage_on_off -> variable_storage_power_imaginary_on_off
variable_reactive_switch_flow -> variable_switch_power_imaginary

variable_shunt_factor -> variable_shunt_admittance_factor
variable_sine -> variable_buspair_sine
variable_sine_on_off -> variable_branch_sine_on_off
variable_storage -> variable_storage_power
variable_storage_mi -> variable_storage_power_mi
variable_storage_mi_on_off -> variable_storage_power_mi_on_off
variable_switch_flow -> variable_switch_power

variable_transformer -> variable_branch_transform
variable_transformer_tm -> variable_branch_transform_magnitude
variable_transformer_ta -> variable_branch_transform_angle

variable_voltage -> variable_bus_voltage
variable_voltage_angle -> variable_bus_voltage_angle
variable_voltage_angle_difference -> variable_buspair_voltage_product_angle
variable_voltage_angle_difference_on_off -> variable_branch_voltage_product_angle_on_off
variable_voltage_imaginary -> variable_bus_voltage_imaginary
variable_voltage_real -> variable_bus_voltage_real
variable_voltage_ne -> variable_ne_branch_voltage
variable_voltage_product -> variable_buspair_voltage_product
variable_voltage_product_ne -> variable_ne_branch_voltage_product
variable_voltage_product_on_off - variable_branch_voltage_product_on_off

variable_voltage_magnitude -> variable_bus_voltage_magnitude_only
variable_voltage_magnitude_sqr -> variable_bus_voltage_magnitude_sqr
variable_voltage_magnitude_sqr_from_ne -> variable_ne_branch_voltage_magnitude_fr_sqr
variable_voltage_magnitude_sqr_from_on_off -> variable_branch_voltage_magnitude_fr_sqr_on_off
variable_voltage_magnitude_sqr_to_ne -> variable_ne_branch_voltage_magnitude_to_sqr
variable_voltage_magnitude_sqr_to_on_off -> variable_branch_voltage_magnitude_to_sqr_on_off
variable_voltage_magnitude_from_on_off -> variable_branch_voltage_magnitude_fr_on_off
variable_voltage_magnitude_to_on_off -> variable_branch_voltage_magnitude_to_on_off
variable_voltage_magnitude_product -> variable_buspair_voltage_product_magnitude
variable_voltage_magnitude_product_multipliers -> variable_buspair_voltage_product_magnitude_multipliers
variable_voltage_magnitude_product_on_off -> variable_buspair_voltage_product_magnitude_on_off
```

Constraint Name Changes
- correct ordering of setpoints to follow variable naming convention
- replace "flow" term with "power"
- replace "loss" with "losses"
- move "_ne" postfix to a prefix, consistency with variable name convention
```
constraint_active_gen_setpoint -> constraint_gen_setpoint_active
constraint_reactive_gen_setpoint -> constraint_gen_setpoint_reactive
constraint_active_dcline_setpoint -> constraint_dcline_setpoint_active
constraint_generation_on_off -> constraint_gen_power_on_off
constraint_gen_active_power_limits -> constraint_gen_active_bounds
constraint_gen_reactive_power_limits -> constraint_gen_reactive_bounds

constraint_flow_losses -> constraint_power_losses
constraint_switch_flow_on_off -> constraint_switch_power_on_off

constraint_loss_lb -> constraint_power_losses_lb
constraint_storage_loss -> constraint_storage_losses

constraint_dcline -> constraint_dcline_power_losses
constraint_dcline_power_limits_from -> constraint_dcline_power_fr_bounds
constraint_dcline_power_limits_to -> constraint_dcline_power_to_bounds

constraint_model_voltage_ne -> constraint_ne_model_voltage
constraint_ohms_yt_from_ne -> constraint_ne_ohms_yt_from
constraint_ohms_yt_to_ne -> constraint_ne_ohms_yt_to
constraint_power_balance_ne -> constraint_ne_power_balance
constraint_thermal_limit_from_ne -> constraint_ne_thermal_limit_from
constraint_thermal_limit_to_ne -> constraint_ne_thermal_limit_to
constraint_voltage_angle_difference_ne -> constraint_ne_voltage_angle_difference
```

**Comment by hakanergun** [comment]
Hello,

For the sake of consistence, I would propose to rename dcline to dcbranch. Especially for the ACDC package where we distinguish between the converters and branches (both lines and cables) this would make more sense.

I think that replacing active & reactive with real and imag makes the variables and constraints look more distinguished and helps for sure in the development of own code.

Cheers,
Hakan


Dr. Dipl.-Ing. Hakan Ergun • Research Expert



Tel.: +32163 21042 | GSM: +32 471 730 564| Fax: +32163 21985



[KU Leuven]<http://www.esat.kuleuven.be/electa>



KU Leuven<http://www.kuleuven.be/> • Dept. Electr. Eng (ESAT) <https://www.esat.kuleuven.be/> • electa<https://www.esat.kuleuven.be/electa>



Kasteelpark Arenberg 10, box 2445 | BE-3001 Heverlee<https://www.google.be/maps/place/Department+of+Electrical+Engineering+ESAT/@50.8620929,4.6837036,17z/data=!3m1!4b1!4m5!3m4!1s0x47c1611616a84773:0x2b4edbaf9cc3e8ba!8m2!3d50.8620895!4d4.6858923>



hakan.ergun@kuleuven.be<mailto:hakan.ergun@kuleuven.be>



[EnergyVille]<http://www.energyville.be/>



EnergyVille<http://www.energyville.be/>• Electrical Networks<http://www.energyville.be/en/networks>



Thor Park 8310 | BE-3600 Genk<https://www.google.be/maps/place/EnergyVille/@50.994894,5.5369231,17z/data=!3m1!4b1!4m5!3m4!1s0x47c0d97298312cf3:0xefd6a2e0f5185a4!8m2!3d50.9948906!4d5.5391118>



hakan.ergun@energyville.be<mailto:hakan.ergun@energyville.be>


Electric power systems embody the physical, intellectual, and symbolic resources of the society that constructs them – Thomas P. Hughes

**Comment by sanderclaeys** [comment]
I like the convention. 

Just to make sure, `<quantity name>` can have multiple words separated by underscores, e.g., `phase_current`?

**Comment by ccoffrin** [comment]
@sanderclaeys, yes that is allowed.  An example from above is `_voltage_product`.

@hakanergun, the name change request is noted.  I would like to keep the names of the components consistent with the data model.  So I would delay this change until https://github.com/lanl-ansi/PowerModels.jl/issues/540 and https://github.com/lanl-ansi/PowerModels.jl/milestone/13 . Note that the final names of the components in PowerModels v1.0 will be dictated by the common transmission data model that I am working with many software developers on.  That is also an important venue to raise this point / request.

**Comment by ccoffrin** [comment]
Upon further review, I added these updates since the initial post,
- top level storage variable declarations have `_power`.  For example, `variable_storage -> variable_storage_power`
- voltage variable declarations now have `_bus` explicitly.  For example, `variable_voltage -> variable_bus_voltage` 

The variable name update block has been revised accordingly.

**Comment by pseudocubic** [comment]
I feel like for me the abbreviations `magn` and `angl` for magnitude and angle actually make it harder to read and type than just having the whole word

**Comment by ccoffrin** [comment]
I am open to spelling out `magnitude` and `angle`.  

My general thought process with the current form was to adopt the Julia function names for complex numbers.  `real` and `imag` are defined in Julia base, so that one was easy.  Unfortunately, I was not able to find a good Julia precedent for `magnitude` and `angle`, so sticking to the first 4 letters seemed consistent with the `imag` instead of `imaginary` convention.  Fixed-with does also have some advantages for presentation in the terminal and text editors.

Thoughts?

**Comment by rb004f** [comment]
Best practices is to use a descriptive name even if slightly longer.  If magn and angl are common power engineering abbreviations I think it is ok, but I am not sure that they are

**Comment by frederikgeth** [comment]
This one looks somewhat inconsistent: `variable_bus_voltage -> variable_bus_voltage_magnitude`, i.e. `variable_bus_voltage_magn`?

Julia does have the function `angle` and `abs` to extract the polar forms. The abbreviation to `angl` bothers me a bit. If we're abbreviating, `mag` and `ang` feel more natural to me. Nevertheles, I actually prefer spelling them out `magnitude` and `angle`. The only place where you really write out these calls is in the problem specification, where it is actually better to be verbose.

**Comment by ccoffrin** [comment]
Thanks for the input @frederikgeth!  I can't believe I forgot about `abs` and `angle`.  So the consensus I am getting is that we prefer this rule for complex quantities,
```
(_real|_imaginary|_magnitude|_angle|_factor)
```
(note, would seem odd to spell out `magnitude` and not `imaginary`)

Add a thumbs up if you support this change.

**Comment by ccoffrin** [comment]
@frederikgeth concerning,
> This one looks somewhat inconsistent: `variable_bus_voltage -> variable_bus_voltage_magnitude`, i.e. `variable_bus_voltage_magn`?

This is actually a fairly pedantic point that I don't have a good solution to at the moment.

The standard voltage definition `variable_bus_voltage`, in the most general case means full complex voltage including the phase.  However, the OPB problem (https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/prob/opb.jl) only requires the magnitude of voltages, phase can be omitted.  So the the question is what do we call the variant of `variable_bus_voltage` that only focuses on representations of the magnitude?  My best solution so far is, `variable_bus_voltage_magnitude`, but this has a name clash with `variable_bus_voltage_magn` which is the non-agnostic function for building `vm`.

Proposals for a better name of the function used in the OPB problem would be much appreciated!

**Comment by frederikgeth** [comment]
Thank you for taking the time for this, I believe it's a great step forward. (_real|_imaginary|_magnitude|_angle|_factor) gets my endorsement! 

Ok, i'm not worried with having an inconsistency for the OPB problem. We can address it later if we see it gets worse over time.

**Comment by ccoffrin** [comment]
@pseudocubic, @rb004f are you happy with the proposed revision `(_real|_imaginary|_magnitude|_angle|_factor)`?

**Comment by ccoffrin** [comment]
Thanks!  I'm proceeding with making the changes in this issue and PR.

**Comment by ccoffrin** [comment]
The updates have been made and I believe we have reached a consensus.  I will leave this issue open for objections over the next 24 hours.  If I do not hear any, I will proceed with merging the PR and preparing the PowerModels v0.17 release.

**Comment by ccoffrin** [comment]
Thanks all for your input, I think the final proposal is great!
