### ISSUE TITLE
LPAC in TNEP

### ISSUE THREAD

**Issue by FlorianShepherd** [lanl-ansi/PowerModels.jl#708]
Dear Carleton and colleagues,

I tried to use the LPACCPowerModel in a TNEP optimization and got:

```
ERROR: LoadError: MethodError: no method matching variable_ne_branch_voltage(::LPACCPowerModel)
Closest candidates are:
  variable_ne_branch_voltage(::AbstractACPModel; kwargs...) 
  variable_ne_branch_voltage(::AbstractDCPModel; kwargs...) 
  variable_ne_branch_voltage(::AbstractWRModel; kwargs...) 
```
as I've understood it, there is no definition of the required TNEP constraint for at least the branch voltage of new branches. I wonder why (is it not possible to define it or just not defined?)? Since I've found your paper: ` Transmission Network Expansion Planning: Bridging the gap between AC heuristics and DC approximations ` I thought it would be great to test the LPAC in a hybrid heuristic approach combining switching optimization and expansion measures. I already implemented it with the DC model to solve the TNEP, but, as you've also stated in the paper, the DC TNEP results are not solving the AC-problem most of the time. What I need are good initial solutions for the heuristic and your results look very promising. 

Maybe I can try to implement the LPAC for TNEP or do you have any other suggestions? 

Thank you in advance and keep up the great work. PowerModels.jl is cool :)!
Best,
Florian

**Comment by ccoffrin** [comment]
Hi @FlorianShepherd!  You are correct, currently the LPAC formulation is only supported for OPF-like problems.  Some function definitions are missing for TNEP and probably OTS as well.

The amount of code to get it working is fairly small, it's the implementation details of the on/off constraints that require some delicate attention.  A PR to add this feature would surely be welcome.  I can probably get to it in the next week or two.

In the meantime you might give the AC-TNEP problem with Juniper+Ipopt a try.  It should be implement and it works for small-ish networks (say <100 buses) in my experience.

**Comment by hakanergun** [comment]
We have an LPAC TNEP within PowerModelsACDC.jl for DC lines and converters, if you are interested in an example.

**Comment by FlorianShepherd** [comment]
Hi Carleton and Hakan, 
I tried the AC-TNEP (ipopt + juniper) and had problems with either convergence or time. It took some time to find a solution and the advantage of the DC-TNEP with gurobi is the super-fast convergence, which is nice if I change the switching position often. My test power systems are between 17-100 buses. 

I'd like to try to implement it but I'm still not very skilled in julia. Maybe you can give me some hints how to? @hakanergun 's example is  very welcomed indeed. Thank you :)! I'll have a look.

**Comment by hakanergun** [comment]
Hi Florian,

For the LPAC TNEP formulation you can find an example here: https://github.com/hakanergun/PowerModelsACDC.jl/blob/master/src/formconv/lpac.jl 

Eventually the DC converter stations come with transformers and filters obeying the AC power flow equations. For instance, the formulation of the transformer power constraints are:https://github.com/hakanergun/PowerModelsACDC.jl/blob/4465dd80667529dda16245a8026f6789ce2ba062/src/formconv/lpac.jl#L233

**Comment by FlorianShepherd** [comment]
Thank you for the hints @hakanergun !

I tried to add the constraints by copying and modifying from the ACP/DCP models. But I'm not sure how to obtain "cs" for ne_branch. Actually, I'm not even sure what "cs" is. Is it something like the base value of Vm at the from or to_bus?

https://github.com/FlorianShepherd/PowerModels.jl/blob/b7874c63f9d37938218ec1200d93d01f9a373a4a/src/form/lpac.jl#L151

`cs     = var(pm, n, :cs_ne, i)` is obviously wrong since cs_ne is not defined. But `cs     = var(pm, n, :branch_ne, i)` is equal to 'z' or isn't it?

I added comments to the code to what I've did.

**Comment by ccoffrin** [comment]
That variable should be added by the `constraint_ne_model_voltage(pm)` function.

The `cs` variable is an approximation of `cos(\theta_i - \theta_j)`, the OPF definitions are here,

https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/form/lpac.jl#L7
https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/form/lpac.jl#L48

The tricky part of the `ne` version is how the on/off constraints are modeled.  Similar to the DC OPT/TNEP problem you need a sufficiently large big-M parameter to turn off the constraints.

**Comment by FlorianShepherd** [comment]
Thanks again @ccoffrin. Unfortunately, I think I have a too little understanding of the whole implementation concept, the julia language, and JuMP. I tried to copy and modify some existing functions (https://github.com/FlorianShepherd/PowerModels.jl/commit/d8dd6945818c676d9eba59f29101e32c43dfdef9) but I don't really know what I'm doing. The compiler throws some key errors ((f_bus, t_bus) in cs_ne is wrong I guess) and I don't know what the big-M is. I probably have to give up for now / postpone my tries because of other work... :/

**Comment by ccoffrin** [comment]
No problem @FlorianShepherd, give me a couple of weeks and I'll try and add it.

**Comment by FlorianShepherd** [comment]
Thank you @ccoffrin for this offer / the effort. I'd really appreciate that!

**Comment by ccoffrin** [comment]
@FlorianShepherd I started to have a look at this and my conclusion is that properly treating the branch on/off constraints in the LPAC formulation is a non-trivial amount of work and I will not plan on implementing it in the near term.  It would require pulling in a nontrivial amount of code from PowerModelsACDC package.  In the meantime, I can recomend that you try the SOC or QC formulations, which are currently working with TNEP in PowerModels.

@hakanergun, a PR that adds support for the LPAC formulation in the OTS and TNEP problems with would be surely welcome!

**Comment by hakanergun** [comment]
I am meaning to implement these, also to have a combined ac/dc tnep. But it might take a while, because need to find a volunteer for that ;).

**Comment by ccoffrin** [comment]
Ok thanks.  Now that I have a better idea of what is involved, I will try to fit it in at some point; just not clear when I will be able to get to it.

**Comment by ccoffrin** [comment]
@FlorianShepherd, this is now in the tagged release, please let us know of any challenges or successes you have with this formulation.

CC @jay-dave

**Comment by FlorianShepherd** [comment]
Thank you @jay-dave and @ccoffrin for implementing this! 

The LPACC model works for a 17-bus test case very well. For a modified RTS case with 81 buses, the solver (Gurobi) seems to get stuck. After several minutes and max. CPU the solver still doesn't converge. This grid has 198 new lines candidates, so maybe it's just a bit much. The DCPPowerModel and the SOCWR converge here.

**Comment by ccoffrin** [comment]
Thanks @FlorianShepherd, I am glad your 17-bus case worked out.  Regarding the larger case, when you consider AC TNEP (and approximations of it), it is quite easy to have voltage support issues in the expanded network.  You might try adding a bunch of reactive power-only generators to the model and see if that help.  I also know that the base-RTS case has a cable with very strong ling charge, there is a shunt on side to balance that, this could also be a source of difficulty in an AC-like model.

**Comment by FlorianShepherd** [comment]
Yep, it's exactly this. Just wanted to share what happened when using the LPAC model. It also works with other test cases. Thank you both again! PowerModels is cool :)
