### ISSUE TITLE
PSSE parser three winding transformer

### ISSUE THREAD

**Issue by hakanergun** [lanl-ansi/PowerModels.jl#712]
I encountered following issue in one of the cases I am using. There is a 3winding transformer in a system for which winding three is out of service, which means that in transformer record STAT = 3 (see record below):
   461,   570,   583,'1 ',3,1,1, 0.00000E+00,-7.00000E-09,2,'TR35        ',3,   1,1.0000,   0,1.0000,   0,1.0000,   0,1.0000,'            '
 7.30612E-3, 2.37030E-1,    70.00, 5.38549E-3, 1.18926E-1,    42.00, 7.19955E-3, 3.80884E-1,    42.00,1.05888, 130.9436

I see that by default a star bus is created, in this case 10461 by default. But as there is nothing connected to the tertiary winding and it being out of service, I get an error as the buspair (461, 10461) is not found.

Would it make sense not to create the star bus if winding 3 is out-of-service?

**Comment by hakanergun** [comment]
Putting "sub_data["br_status"] = Int(transformer["STAT"] == 1)" in line 493 of PSSE.jl where the sub transformer data is written solves the problem, as then the br_status of the sub transformer becomes 0, and the bus pair is removed.

**Comment by hakanergun** [comment]
Putting the br_status of the out of service winding as in psse.jl                 
                    if transformer["STAT"] > 1
                         sub_data["br_status"] = 1 - Int(transformer["STAT"] == m)
                    else
                        sub_data["br_status"] = transformer["STAT"]
                    end

seems to solve the problem.

**Comment by hakanergun** [comment]
Another issue I found on this is that, if multiple 3-winding transformers are connected to the same bus, the star-bus number is not chaged, so it looks like these 9-transformers are connected to the same internal star bus 10042:

    42,   474,   535,'1 ',3,1,1, 1.40000E-03,-9.90152E-03,2,'TR27        ',1,   1,1.0000,   0,1.0000,   0,1.0000,   0,1.0000,'            '
 4.56000E-4, 4.09975E-2,   500.00, 8.42626E-4, 3.47203E-2,   167.00, 9.32267E-4, 8.20306E-2,   167.00,1.07817, 141.4716
1.00000, 380.000,   0.000,   500.00,   500.00,   500.00, 1,    474, 1.15000, 0.85000, 1.06000, 1.02000,  21, 0, 0.00000, 0.00000,  0.000
1.00000, 150.000,   0.000,   500.00,   500.00,   500.00, 0,      0, 1.00000, 1.00000, 1.10000, 0.90000,  33, 0, 0.00000, 0.00000,  0.000
1.00000,  50.000,-150.000,   167.00,   167.00,   167.00, 0,      0, 1.00000, 1.00000, 1.10000, 0.90000,  33, 0, 0.00000, 0.00000,  0.000
    42,   230,   536,'1 ',3,1,1, 1.40000E-03,-9.90152E-03,2,'TR28        ',1,   1,1.0000,   0,1.0000,   0,1.0000,   0,1.0000,'            '
 4.56000E-4, 4.09975E-2,   500.00, 8.42626E-4, 3.47203E-2,   167.00, 9.32267E-4, 8.20306E-2,   167.00,1.07813, 141.4732
1.00000, 380.000,   0.000,   500.00,   500.00,   500.00, 1,    230, 1.15000, 0.85000, 1.06000, 1.02000,  21, 0, 0.00000, 0.00000,  0.000
1.00000, 150.000,   0.000,   500.00,   500.00,   500.00, 0,      0, 1.00000, 1.00000, 1.10000, 0.90000,  33, 0, 0.00000, 0.00000,  0.000
1.00000,  50.000,-150.000,   167.00,   167.00,   167.00, 0,      0, 1.00000, 1.00000, 1.10000, 0.90000,  33, 0, 0.00000, 0.00000,  0.000
    42,   230,   537,'1 ',3,1,1, 1.40000E-03,-9.90152E-03,2,'TR29        ',1,   1,1.0000,   0,1.0000,   0,1.0000,   0,1.0000,'            '
 4.56000E-4, 4.09975E-2,   500.00, 8.42626E-4, 3.47203E-2,   167.00, 9.32267E-4, 8.20306E-2,   167.00,1.07813, 141.4732
1.00000, 380.000,   0.000,   500.00,   500.00,   500.00, 1,    230, 1.15000, 0.85000, 1.06000, 1.02000,  21, 0, 0.00000, 0.00000,  0.000
1.00000, 150.000,   0.000,   500.00,   500.00,   500.00, 0,      0, 1.00000, 1.00000, 1.10000, 0.90000,  33, 0, 0.00000, 0.00000,  0.000
1.00000,  50.000,-150.000,   167.00,   167.00,   167.00, 0,      0, 1.00000, 1.00000, 1.10000, 0.90000,  33, 0, 0.00000, 0.00000,  0.000

**Comment by ccoffrin** [comment]
Thanks for finding these!  Will work on them for the next release. A PR is surely welcome.  However, if you have the time to extend some of the cases in `test/data/pti` to exhibit these issues that would also be helpful.

**Comment by hakanergun** [comment]
I will try to create a PR for both issues in the coming days. As for the second issue it seems to that the best course to use unique id for the transformers when the .raw records are read, and base the star bus bus number on that, as the name can be any string apparently and there is no other unique id. I will have a look how to best to do it with least code ;).
