### ISSUE TITLE
Getting error while attempting to install the BFAPowerModels package

### ISSUE THREAD

**Issue by gaadis** [lanl-ansi/PowerModels.jl#719]
I'm getting an error while trying to instal the BFAPowerModel package to solve an OPF using the BFM. My objective is to solve an OPF  or just a power flow problem for a distribution network using the BFM.
My code is below:
using BFAPowerModels, Ipopt, JuMP

network_data = BFAPowerModels.parse_matpower("case118.m")
results = run_opf_bf(network_data, with_optimizer(Ipopt.Optimizer))

When I ran the above code, it gave me the error below
ERROR: LoadError: ArgumentError: Package BFAPowerModels not found in current path:
- Run `import Pkg; Pkg.add("BFAPowerModels")` to install the BFAPowerModels package.

When I tried to install the package, I got the error message is below:
julia> Pkg.add("BFAPowerModels")
ERROR: The following package names could not be resolved:
 * BFAPowerModels (not found in project, manifest or registry)

Any assistance will be greatly appreciated.

Thanks.
Gadi

**Comment by ccoffrin** [comment]
As far as I know there is no package called `BFAPowerModels`.  I think what you want something like,

install with,
```
] add PowerModels, Ipopt, JuMP
```

run a BFA opf problem with,
```
using PowerModels, Ipopt

network_data = PowerModels.parse_file("case118.m")
results = run_opf_bf(network_data, BFAPowerModel, Ipopt.Optimizer)
```

**Comment by ccoffrin** [comment]
test

**Comment by gaadis** [comment]
I have attempted running the code below 

using PowerModels, Ipopt

network_data = PowerModels.parse_file("case118.m")
results = run_opf_bf(network_data, BFAPowerModel, Ipopt.Optimizer)

and the following error came up

ERROR: LoadError: UndefVarError: BFAPowerModel not defined
Stacktrace:
 [1] top-level scope at C:\Users\Gadis\Dropbox\NMPC\Julia\PowerModel.jl:20
in expression starting at C:\Users\Gadis\Dropbox\NMPC\Julia\PowerModel.jl:20

If I remove the BFAPowerModel, then I get the error below

ERROR: LoadError: MethodError: no method matching run_opf_bf(::Dict{String,Any}, ::Type{Ipopt.Optimizer})
Closest candidates are:
  run_opf_bf(::Any, ::Type{T}, ::Any; kwargs...) where T<:AbstractBFModel at C:\Users\Gadis\.juliapro\JuliaPro_v1.3.1-2\packages\PowerModels\3N78S\src\prob\opf_bf.jl:3

Your feedback is appreciated.

Thanks

**Comment by ccoffrin** [comment]
I tested with PowerModels v0.17.0 and it works.  Make sure you are using the latest version of PowerModels.  You can check with, `] status` and you can try updating your packages with `] update`

**Comment by ccoffrin** [comment]
I am going to close this becouse it seems to be resolved.  For future refrence, this type of first-steps question is best directed at https://discourse.julialang.org/.
