### ISSUE TITLE
Branch results

### ISSUE THREAD

**Issue by upslowlander** [lanl-ansi/PowerModels.jl#720]
Hello

I am running AC power flow and "branch" is not produced in "solution"using the latest version. I have also tried this:

result = run_ac_pf(network_data, Ipopt.Optimizer,
    setting = Dict("output" => Dict("branch_flows" => true)))

Still, nothing. 

The latter used to work in a previous version. Has there been a change. 

Thank you
Best Regards
Panos

**Comment by ccoffrin** [comment]
Hi Panos, in v0.15 there were a number of changes in how solutions are reported and `setting = Dict("output" => Dict("branch_flows" => true)))` is no longer used.  Additionally in v0.16 major changes were made to PowerFlow ([details here](https://lanl-ansi.github.io/PowerModels.jl/stable/power-flow/)).

As of v0.17, to get the branch flow values into the network data from a power flow solution you do this,
```
result = run_ac_pf(network_data, Ipopt.Optimizer)
update_data!(network_data, result["solution"])
flows = calc_branch_flow_ac(network_data)
update_data!(network_data, flows)
```
You can also use the `flows` dict directly if you don't need it alongside the other data.

**Comment by upslowlander** [comment]
Thank you, very much. That worked.
