### ISSUE TITLE
Adding constraints after instantiating IV-model

### ISSUE THREAD

**Issue by fnbillimoria** [lanl-ansi/PowerModels.jl#736]
Hi, I am attempting to add additional constraints into the existing PowerModels IV-formulation.  I have instantiated the model, and then added a constraint on the internal variable vi, however I am getting a variable declaration error "UndefVarError: vi not defined".  Are the variables declared in the PowerModels instantiation functions not in global scope?  Am i refereing the variable incorrectly?  ( I note that the variable name in the internal function is preceded by the nw number i.e. 0_vi).  Would be grateful for any thoughts.  Many thanks!

using Ipopt
using JuMP
using PowerModels

case_file = "C:/Users/farhad/OneDrive - Nexus365/DPhil/Scripts/Powermodel/PowerModels/test/data/matpower/case3.m"
pm_dict = parse_matpower(case_file)
aref = PowerModels.build_ref(pm_dict)[:nw][0]

pm = PowerModels.instantiate_model(pm_dict,IVRPowerModel,build_opf_iv_f)
iv_model = pm.model

@constraint(iv_model, vi[1] >= 0.7)

**Comment by ccoffrin** [comment]
> Are the variables declared in the PowerModels instantiation functions not in global scope? 

That is correct, they are not in the global scope.  You need to use the the `var` function to extract them from the PowerModel struct like so,

```
using Ipopt; using JuMP; using PowerModels

case_file = "..."
pm_dict = parse_matpower(case_file)
pm = PowerModels.instantiate_model(pm_dict, IVRPowerModel, build_opf_iv)

vi = var(pm, :vi)
@constraint(pm.model, vi[1] >= 0.7)
```
in most cases you can even do,
```
@constraint(pm.model, var(pm, :vi)[1] >= 0.7)
```
But that can cause an issue if you are using `@NLconstraint`.

Thanks for asking these question I can see you are quickly becoming an expert user!  I do recommend we move future inquiries to https://discourse.julialang.org/, that location is the best place for these types of questions (feel free to @ mention me there for the fastest response).  This issue tracker is best for posting suspected bugs and feature requests for the software.

**Comment by fnbillimoria** [comment]
Thanks @ccoffrin that is most appreciated, and will post on the discourse forum in future! :)
