### ISSUE TITLE
pg_sqr Constraint in Conic Formulations

### ISSUE THREAD

**Issue by wzhangw** [lanl-ansi/PowerModels.jl#743]
Hi, I have a question about the rotated second order cone constraint for pg_sqr: 

https://github.com/lanl-ansi/PowerModels.jl/blob/a572ca03eabf2392a542e33d72653a69e46e48db/src/core/objective.jl#L209

My understanding is that pg_sqr is replacing pg^2 so that the objective is linear, but according to JuMP's documentation on `[JuMP.RotatedSecondOrderCone](https://jump.dev/JuMP.jl/dev/constraints/#JuMP.RotatedSecondOrderCone)` the constraint currently implemented is

|pg| <= 2 * 0.5 * pg_sqr = pg_sqr

so is pg_sqr attaining the value of |pg| instead of pg^2?

**Comment by ccoffrin** [comment]
You have to look carefully at the JuMP docimentation to see that it's the L2 norm, i.e. `‖(x,y)‖_2`.  So in this case we get, `||pg||_2 <= 2 * 0.5 * pg_sqr` which is `pg^2 <= pg_sqr`.  Does that help clarify the implementation?

**Comment by wzhangw** [comment]
Oh I see the left hand side is actually square of L2 norm... Thanks for the clarification!
