### ISSUE TITLE
Mosek error in solving opf with SDPWRMPowerModel 

### ISSUE THREAD

**Issue by jchen975** [lanl-ansi/PowerModels.jl#744]
Hi, I'm trying to do a comparison between SOC, QC and SDP like the one provided in the documentation. All others work fine, but Mosek is giving me the following error:
```
ERROR: MosekError(3915, "There is no barx available for the solution type 2.")
```
when I tried to run
```
mosek = optimizer_with_attributes(Mosek.Optimizer, "QUIET"=>true)
sdp = run_opf(network, SDPWRMPowerModel, mosek)
```
on a few small cases (3, 30, 118-bus) from the PGLib-OPF. I searched around and found this issue in another repository:
https://github.com/wzhangw/ComplexBC/issues/2. I tried adding `MosekTools v0.9.3` as suggested but to no avail. I also tried `SparseSDPWRMPowerModel` and got the same error. 

I'm using the free academic license from Mosek, if that matters. I'm using Julia v1.5.2, and updated all packages other than `MosekTools`. 

Could you point me to a way to fix this?

**Comment by jchen975** [comment]
Update: it is working if I don't include `using Mosek` at the top of my file... not sure why. Please feel free to close the issue!

**Comment by ccoffrin** [comment]
Hi @jchen975, I am not sure what would be causing this issue but I am glad to hear that you have found a work around.  My best guess would be that some of the function names in Mosek overlapped with another package you were calling `using` on and this lead to some unexpected behavior.

CC @ulfworsoe, just in case he has any ideas.

**Comment by ulfworsoe** [comment]
It sounds likely that there is a symbol clash, but I wouldn't even know where to begin looking.
