### ISSUE TITLE
Getting INVALID_MODEL error while solving RMSE

### ISSUE THREAD

**Issue by gaadis** [lanl-ansi/PowerModels.jl#748]
I'm attempting to minimize an RMSE where the optimized coefficients alpha and beta give a forecasted value (xnext) from the original value (x_k). 

![image](https://user-images.githubusercontent.com/37007341/102705932-2c1c5700-424a-11eb-9992-4255f36d14fe.png)

My code is below

x_k = EstimatedVoltage;
    # Initialize a JuMP Optimization Model
    fcst = Model(with_optimizer(Ipopt.Optimizer, print_level=0))

    # Defining variables
    @variable(fcst, 0.001 <= alpha[i in 1:bn] <= 0.99)
    @variable(fcst, 0.001 <= beta[i in 1:bn] <= 0.99)
    @variable(fcst, a_k[i in 1:bn] )
    @variable(fcst, b_k[i in 1:bn])
    @variable(fcst, xnext[i in 1:bn])
    @variable(fcst, Error[i in 1:bn])

    # Objective function
    @NLobjective(fcst, Min, sqrt(sum(xnext[i]-x_k[i] for i in 1:bn)^2/bn))
    #@objective(fcst, Min, sum(xnext[i]-x_k[i] for i in 1:bn)^2/bn)
    #@objective(fcst, Min, sqrt(msd(x_k,x_k)))

bn = 33
for i in 1:bn

    if i == 1
        apast = x_k[1,1]
        bpast = x_k[1,1] - x_k[2,1]
     @constraint(fcst, a_k[i] ==  apast )
     @constraint(fcst, b_k[i] ==  bpast)
     @constraint(fcst, xnext[i] ==  a_k[i] + b_k[i])

    else
    apast = a_k[i-1]
    bpast = b_k[i-1]
    @constraint(fcst, a_k[i] ==  alpha[i]*x_k[i] + (1 - alpha[i]*(apast + bpast)))
    @constraint(fcst, b_k[i] ==  beta[i]*(a_k[i] - apast) + (1 - beta[i]*bpast))
    @constraint(fcst, xnext[i] ==  a_k[i] + b_k[i])
    @constraint(fcst, beta[i] <= 0.99*alpha[i])
    end
end
    # Solve the optimization problem
    JuMP.optimize!(fcst)
    Alpha = JuMP.value.(alpha)
    Beta = JuMP.value.(beta)
    Xnext = JuMP.value.(xnext)
    Level = JuMP.value.(a_k)
    Trend = JuMP.value.(b_k)

    # Check that the solver terminated without an error
    println("The solver termination status is $(termination_status(fcst))")

    # Check the value of the objective function
    RMSE = objective_value(fcst)

#Below are the values I used for x_k
EstimatedVoltage = [
0.996297
0.994941
0.974948
0.969849
0.964425
0.947913
0.944859
0.935953
0.929733
0.920502
0.92148
0.918334
0.917048
0.913723
0.914564
0.914005
0.908324
0.909003
0.991995
0.98336
0.991156
0.987132
0.977665
0.968546
0.965581
0.945011
0.937952
0.925111
0.916413
0.91718
0.90907
0.909483
0.911058]

**Comment by ccoffrin** [comment]
Hi @gaadis, as far as I can tell this inquiry is not directly related to PowerModels and appears to be a Julia/JuMP.  I recommend you repost it on the JuliaLang forum here, https://discourse.julialang.org/

**Comment by gaadis** [comment]
Will do. Thank you.
    On Sunday, December 20, 2020, 07:11:25 PM MST, Carleton Coffrin <notifications@github.com> wrote:  
 
 


Hi @gaadis, as far as I can tell this inquiry is not directly related to PowerModels and appears to be a Julia/JuMP. I recommend you repost it on the JuliaLang forum here, https://discourse.julialang.org/
