### ISSUE TITLE
Export PTI data

### ISSUE THREAD

**Issue by jbarberia** [lanl-ansi/PowerModels.jl#752]
Is there an ```export_pti``` function to write the networks as ```export_matpower```?

How could it be implemented in PowerModels?

**Comment by ccoffrin** [comment]
Hi @jbarberia, at the moment this is not available but it is a good suggestion.

The `export_matpower` function should provide a good template for how an `export_pti` could be implemented.

**Comment by jbarberia** [comment]
@ccoffrin, I just saw the ```export_matpower``` function, I'm going to try to implement it.

Some questions:

- Should I check the file extension? ```export_matpower``` doesnt have it (see [here](https://github.com/lanl-ansi/PowerModels.jl/blob/83fb85cfe2ca71ac2b927f0af6e38721c0593fa6/src/io/matpower.jl#L701)). You can do something like ```export_matpower("filename_without_extension", data)``` and its works.

- Would it be better to add functions in ```psse.jl``` like ```_pm2psse_generator!(pm_data, pti_data)``` (opposite of [this](https://github.com/lanl-ansi/PowerModels.jl/blob/83fb85cfe2ca71ac2b927f0af6e38721c0593fa6/src/io/psse.jl#L183))  or not?

- What to do with three winding transformers? export it as three two-windings transformers and the star-bus or recreate the three-winding transformer again?

**Comment by ccoffrin** [comment]
Sounds good @jbarberia!

- checking the file extension is a good idea.  You probably want to allow both `.RAW` and `.raw`.  I personally prefer the use of lower case version in this package
- This is mostly a matter of style, so I am open to defining new functions or not (similar to `export_matpower`). If you are not going call a function in multiple locations, there is limited utility to adding the function definitions.
- The inverse problem can be challenging, so I would skip this in the first version and clearly document the limitations of function.  In particular the limited set of PSSE features when one can expect it to be idempotent. 

As you work along make sure to have a look at the Matpower export tests here,

https://github.com/lanl-ansi/PowerModels.jl/blob/83fb85cfe2ca71ac2b927f0af6e38721c0593fa6/test/matpower.jl#L212

We will need similar tests for `export_pti` and we will have to make some choices on what level of idempotent we will want to support (note you can use `import_all=true` to import all of unsupported data fields from a raw file).

**Comment by jbarberia** [comment]
@ccoffrin, Tell me what you think about doing something like [this](https://github.com/jbarberia/PowerModels.jl/commit/cbb7384dee3d11fcea8b827d676112ac8464d4e4)? 

If you agree I can continue with the rest.

**Comment by ccoffrin** [comment]
@jbarberia I put some initial comments in the code file that you linked, can you see them?

As a meta comment I also saw a number of edge cases that will fail when data is missing.  I also recommend that you try the following work flow to catch some of those, "Load a Matpower case, export as PTI".

**Comment by jbarberia** [comment]
@ccoffrin I saw your comments, I will follow them.

I'm going to extend the tests to detect these borderline cases.

Thanks for seeing it!

**Comment by ccoffrin** [comment]
closed by #753
