### ISSUE TITLE
Track solver progress

### ISSUE THREAD

**Issue by mdinh186** [lanl-ansi/PowerModels.jl#759]
Hi there, 

I'm trying to get access to the intermediate state of the optimization problem, at each iteration. 

```solver = JuMP.with_optimizer(Ipopt.Optimizer)```

Is there any way to have a custom callback function which stores the output log or prints out `problem.x` ?

Thanks

**Comment by ccoffrin** [comment]
Hi @mdinh186, I am not aware of a function like this for Ipopt but there are callbacks in other solvers.  This is really a question about JuMP than PowerModels so you may have better luck if you direct your question to the boarder Julia community here, https://discourse.julialang.org/c/domain/opt/13
