### ISSUE TITLE
Jacobian Support for Basic Network Data

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#762]
A Jacobian matrix support to the Basic Network Data features.  Key features include,
- building a from-scratch AC Power Flow solver on basic data
- analysis p/q vs vm/theta sensitive (i.e. Jacobian were all buses are PQ)
- from-scratch fast decoupled load flow solver (optional)

**Comment by jbarberia** [comment]
@ccoffrin, I started working to contribute to this issue. Tell me what you think about [this](https://github.com/jbarberia/PowerModels.jl/commit/1595190e54c10aa41638bc3c9c84a928db59e0df).

I know it can be improved (specially the AC Power Flow solver). Surely this week I can finish it and make a pull request.

**Comment by ccoffrin** [comment]
@jbarberia thanks for taking a pass at this.  I only had a quick pass but here are some initial comments,

- I would prefer to not have a function with the signature `calc_basic_jacobian_matrix(data::Dict{String,<:Any}, V::Array{Complex{Float64}, 1})`, a user can change the bus type in the dict before sending it to `calc_basic_jacobian_matrix`
- I would move the `calc_basic_bus_type` code into `calc_basic_jacobian_matrix` I am not sure it has many uses outside of that function.
- I would move the `compute_basic_ac_pf` code into the package tests.  Users who would like to solve AC-PF (on basic data or not) should use `run_ac_pf` or `compute_ac_pf`.

I'll also loop in @molzahn as this was a feature he requested.

**Comment by ccoffrin** [comment]
closed by #777
