### ISSUE TITLE
`SparseSDPWRMPowerModel` doesn't support multinetwork without nw=0

### ISSUE THREAD

**Issue by claytonpbarrows** [lanl-ansi/PowerModels.jl#769]
I get an error in the latest version of PM when integrating with PowerSimulations.jl.
I believe that [this line](https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/form/wrm.jl#L140) should be 
`cadj, lookup_index, ordering = _chordal_extension(pm, nw)`

**Comment by ccoffrin** [comment]
Thanks for the report!  I have a hunch for what is going on but is it easy to make a MWE that exhibits the issue that I can incorporate into the tests?

**Comment by ccoffrin** [comment]
Should be fixed on master, if you could confirm it is working for you and close this, that would be great.

**Comment by claytonpbarrows** [comment]
Everything appears to work. Thanks!
