### ISSUE TITLE
Are there Include Lagrange multipliers in results from OPF?

### ISSUE THREAD

**Issue by Crueda96** [lanl-ansi/PowerModels.jl#772]

**Comment by Crueda96** [comment]
Is it possible to calculate the nodal LMP prices for each bus in the AC OPF case with PowerModels?

**Comment by ccoffrin** [comment]
Yes, have a look at this issue, https://github.com/lanl-ansi/PowerModels.jl/issues/409

Should be working for AC OPF as well these days.  Let me know if it is not.

**Comment by ccoffrin** [comment]
I confirmed this working for the AC model as of PM v0.18
