### ISSUE TITLE
correct_reference_buses! fails when the largest generator in component has status 0

### ISSUE THREAD

**Issue by bluejuniper** [lanl-ansi/PowerModels.jl#776]
It appears that the helper function `_correct_reference_buses!` does not check generator status when creating the list of generators by connected components `cc_gens.`  Possible fix: change line `if haskey(bus_to_cc, bus_id)` to `if haskey(bus_to_cc, bus_id) && gen["gen_status"]`== 1

**Comment by ccoffrin** [comment]
Nice catch!  Will fix soon, before the end of this week.

**Comment by ccoffrin** [comment]
Assuming this is now fixed.
