### ISSUE TITLE
AmplNLWriter + Bonmin not working for the simplest test case

### ISSUE THREAD

**Issue by jay-dave** [lanl-ansi/PowerModels.jl#782]
I have the following configuration:
  - AmplNLWriter v0.7.1
-   PowerModels v0.18.2
-   Julia v1.5.4
-   JuMP v0.21.4

My code to run the simple 3 bus tnep problem from the test files: 
file = "path/PowerModels/test/data/matpower/case3_tnep.m"
data = PowerModels.parse_file(file)
calc_thermal_limits!(data)
bonmin_solver= JuMP.optimizer_with_attributes(() -> AmplNLWriter.Optimizer("path/Bonmin.exe"))
resultAC_bonmin     =  run_tnep(data, ACPPowerModel, bonmin_solver; setting = s)
(it solves with Juniper solver as done in tnep.jl file of the package)

**I get the following warnings:**
[warn | InfrastructureModels]: The given optimizer does not provide the SolveTime() attribute, falling back on @timed.  This is not a rigorous timing value.
[warn | InfrastructureModels]: model has no results, solution cannot be built

**result:**
"termination_status" =>  OTHER_ERROR::TerminationStatusCode = 24
"objective" => NaN

I think that there is an issue with the configuration (versions) or solve definition (JuMP.optimizer_with_attributes(...)).  There should be a solution with Bonmin as the test case is feasible and simple. Can someone help me out to figure out the issue?

**Comment by ccoffrin** [comment]
I am going to defer this question to @odow, it looks to be to be an issue with the `AmplNLWriter` and not PowerModels.

**Comment by odow** [comment]
I can't run the code because I don't know what `s` is. 

Where did you get the Bonmin executable from? 

Did the solver lot give any indication as to what went wrong?

Does this problem have integer variables? Or is it a pure LP?

Use `Bonmin_jll` instead
```Julia
using AmplLNWriter, Bonmin_jll
bonmin_solver = () -> AmplNLWriter.Optimizer(Bonmin_jll.amplexe)
```
You could also try Couenne
```Julia
using AmplLNWriter, Couenne_jll
bonmin_solver = () -> AmplNLWriter.Optimizer(Couenne_jll.amplexe)
```

**Comment by ccoffrin** [comment]
To answer the question about model classes, run_tnep + ACPPowerModel, is a nonconvex MINLP.

**Comment by jay-dave** [comment]
@odow @ccoffrin thanks!
changing the solver declaration helped as suggested. i.e. bonmin_solver = () -> AmplNLWriter.Optimizer(Bonmin_jll.amplexe)
