### ISSUE TITLE
Conversion between formulations

### ISSUE THREAD

**Issue by iagochavarry** [lanl-ansi/PowerModels.jl#802]
I'm benchmarking power flow formulations (solve time, active/reactive power flow, voltage magnitudes, and angles), and I'm having some trouble comparing the results between the formulations. Is there an implemented way to map/convert formulation results?

For example, IVR -> ACP, or ACT -> ACP.

**Comment by ccoffrin** [comment]
@iagochavarry this is a good question! There is a little known feature called `solution_processors=[sol_data_model!]` which will post-process the model solution into the formulation of the data model (which is ACP, as you would like).  If you make calls like,
```
result = run_opf(data, ACRPowerModel, solver, solution_processors=[sol_data_model!])
```
It should have the desired effect.  I do not know if `sol_data_model!` has been implemented yet for `IVR` or `ACT`, if not I can look into this.
