### ISSUE TITLE
`sol_component_value_edge` should call `_IM.sol_component_value_edge`

### ISSUE THREAD

**Issue by matteorossini** [lanl-ansi/PowerModels.jl#811]
`sol_component_value_edge` should call `_IM.sol_component_value_edge` instead of `_IM.sol_component_value`:
https://github.com/lanl-ansi/PowerModels.jl/blob/797008d6c54bb410fab14011b54a3e0aaada40ea/src/core/solution.jl#L34-L36

**Comment by ccoffrin** [comment]
Great catch!  Fix is on its way.
