### ISSUE TITLE
Convert the formulation to JUMP model

### ISSUE THREAD

**Issue by lidingxu** [lanl-ansi/PowerModels.jl#824]
Dear all,
  I want to modify ACOPF models to add some constraints. So I need a formulation in JuMP as a model.
  Is there any way to obtain a JuMP representation of the SDP/SOCP relaxation from PowerModels.jl?
  Thank you.

Liding

**Comment by ccoffrin** [comment]
Hi @lidingxu.  I am not 100% sure that I follow your question. Under the hood PowerModels builds JuMP models and sends them to solvers. The quick-start guide provides one example of how you can use PowerModels to [build a JuMP model without solving it](https://lanl-ansi.github.io/PowerModels.jl/stable/quickguide/#Building-PowerModels-from-Network-Data-Dictionaries).  If you would prefer a _from scratch_ JuMP model some examples are available [here](https://github.com/lanl-ansi/PowerModelsAnnex.jl/tree/master/src/model).  Does either of these cover what you need?

Also for future reference, Q&A about Julia packages is best directed to the Julia forms here, https://discourse.julialang.org/

**Comment by lidingxu** [comment]
Hi @ccoffrin, thank you. The from scratch JuMP model covers my need.
