### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by ufechner7** [lanl-ansi/PowerModels.jl#826]
I tried the example from the quickstart guide, but it does not work:
```
using PowerModels
using Ipopt

solve_ac_opf("matpower/case3.m", Ipopt.Optimizer)
```
Gives the error:
```
ERROR: SystemError: opening file "/home/ufechner/repos/examples/first_example.jl": Datei oder Verzeichnis nicht gefunden
Stacktrace:
  [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
    @ Base ./error.jl:174
  [2] #systemerror#68
    @ ./error.jl:173 [inlined]
  [3] systemerror
    @ ./error.jl:173 [inlined]
  [4] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing)
    @ Base ./iostream.jl:293
  [5] open
    @ ./iostream.jl:282 [inlined]
  [6] open(f::Base.var"#364#365"{String}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:328
  [7] open
    @ ./io.jl:328 [inlined]
  [8] read
    @ ./io.jl:436 [inlined]
  [9] _include(mapexpr::Function, mod::Module, _path::String)
    @ Base ./loading.jl:1249
 [10] include(fname::String)
    @ Base.MainInclude ./client.jl:451
 [11] top-level scope
    @ REPL[1]:1
```
A working example file should be included in the package.

**Comment by ccoffrin** [comment]
Hi @ufechner7.  This is a good point that I have toiled with over the years.  PowerModels does not ship with datasets. So, a priori, I would not know the path to a specific case on a given users computer, so right now we only provide an illustrative example that does not work.

One option would be to access one the datasets that is used for testing the package like this,

"$(joinpath(dirname(pathof(PowerModels)), ".."))/test/data/matpower/case3.m"

But this makes it look much more complex and tedious than it really is in practice.

In a fairly recent development there is a new Julia package called [PGLib](https://github.com/noahrhodes/PGLib.jl) which makes the standard OPF datasets easy to access in from inside Julia.  This could be another option, if we added an extra dependency to the examples.

What are your thoughts?
