### ISSUE TITLE
Accessing dual values

### ISSUE THREAD

**Issue by gcherot** [lanl-ansi/PowerModels.jl#841]
I want to retrieve the dual values associated with each constrain of the OPF (bus min/max voltages, line max loadings...). Is there a way to do that?

I am aware that this question was raised 2 years ago (https://discourse.julialang.org/t/powermodelsannex-jl-obtaining-duals/43535) but since I am a total beginner in Julia (I use the PandaPower interface), I was not able to follow the instruction given by @ccoffrin .

This might also be related to #661 . If so, sorry about the duplicate issue.

Thank you very much for your answer.

**Comment by ccoffrin** [comment]
I think the most relevant discussion is here, https://github.com/lanl-ansi/PowerModels.jl/issues/409#issuecomment-435498492

The short answer is that there is partial support for getting duals in PowerModels.   Try something like this,
```
result = run_dc_opf("../test/data/matpower/case5.m", nlp_solver, setting = Dict("output" => Dict("branch_flows" => true, "duals" => true)))
```
and look for them in the solution dictionary.

If that serves your needs we can close this issue.  If not, maybe we can add your feature request to the discussion in #409?

**Comment by gcherot** [comment]
Unfortunately, I need all dual values. For example, I would like to have the dual values associated with voltage constrains.
I close this issue and I will add a feature request in #409.
