### ISSUE TITLE
GenericPowerModel

### ISSUE THREAD

**Issue by babak1995** [lanl-ansi/PowerModels.jl#845]
Hi, 

I'm trying to define a function in PowerModels.jl, but receiving the following error:

_function my_function(pm::GenericPowerModel{T})
    ...
end_

**UndefVarError: GenericPowerModel not defined**

I also tried:

_function my_function{T}(pm::GenericPowerModel{T})
    ...
end_

Thank you for your help.

**Comment by ccoffrin** [comment]
You should use `AbstractPowerModel` instead. `GenericPowerModel` is from an older versions of PowerModels.  Possibly some documentation is out of date, where did you find the reference to `GenericPowerModel`?

**Comment by ccoffrin** [comment]
Closing due to no clear action and lack of activity.
