### ISSUE TITLE
Voltage magnitude increases

### ISSUE THREAD

**Issue by antonhinneck** [lanl-ansi/PowerModels.jl#851]
I need PowerModels to validate a power flow solution I obtained. Using solve_pf (ACPPowerModel) on a simple linear grid with 4 buses (in own matpower file), the following result is produced:

vm_1: 1.0
vm_2: 1.02146627234797
vm_3: 1.0285057423141553
vm_4: 1.0302486103076218

A generator is located at bus 1. All other buses have loads connected.

Problem: I would expect vm to drop.

This commonly happens when fbus and tbus are swapped in a formulation for example. I probably just did something wrong though - can't seem to figure out what, however. 

I would be thankful for  any pointers you may be able to provide.

**Comment by ccoffrin** [comment]
I would have to see the dataset to know for sure, but this can happen if
reactive power is injected by the loads (or shunts) in the non-generator
buses.  Have a look at that.

**Comment by antonhinneck** [comment]
Sorry about that. Yes, it was indeed due to reactive power injection. Thank you!
