### ISSUE TITLE
Trying to solve DC but PowerModels crash with a Quadratic function error

### ISSUE THREAD

**Issue by DimaLPorNLP** [lanl-ansi/PowerModels.jl#852]
Dear community,
to begin with I would like to congratulate the authors of PowerModels for their excellent work. I was really surprised by the simplicity of the code and the variety of formulations, and the general code organization. Congratulations. I have a few glitches to report however. Perhaps the fix is relatively easy. So, for several models of pglib-opf trying to use Tulip with DCPPowerModel approximation results in a fast and successful solution, see below

```julia> solve_opf("pglib_opf_case118_ieee.m", DCPPowerModel, Tulip.Optimizer)
Dict{String, Any} with 8 entries:
  "solve_time"         => 10.9951
  "optimizer"          => "Tulip"
  "termination_status" => OPTIMAL
  "dual_status"        => FEASIBLE_POINT
  "primal_status"      => FEASIBLE_POINT
  "objective"          => 93100.7
  "solution"           => Dict{String, Any}("baseMVA"=>100.0, "branch"=>Dict{String, Any}("1"=>Dict{String, Any}("qf"=>NaN, "qt"=>NaN, "pt"=>0.0717168, "pf"=>-0.0717168),…
  "objective_lb"       => 93100.7

julia> solve_opf("pglib_opf_case3375wp_k.m", DCPPowerModel, Tulip.Optimizer)
Dict{String, Any} with 8 entries:
  "solve_time"         => 1.42749
  "optimizer"          => "Tulip"
  "termination_status" => OPTIMAL
  "dual_status"        => FEASIBLE_POINT
  "primal_status"      => FEASIBLE_POINT
  "objective"          => 7.31701e6
  "solution"           => Dict{String, Any}("baseMVA"=>100.0, "branch"=>Dict{String, Any}("3935"=>Dict{String, Any}("qf"=>NaN, "qt"=>NaN, "pt"=>0.00951103, "pf"=>-0.00951…
  "objective_lb"       => 7.31701e6
```

However, with some others this does not happen
```
ERROR: MathOptInterface.UnsupportedAttribute{MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarQuadraticFunction{Float64}}}: Attribute MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarQuadraticFunction{Float64}}() is not supported by the model.
```

I am wondering where the Quadratic function came from. DC is supposed to be linear and the objective should be losses or not? Is it possible that a quadratic (generation cost) objective is defined despite the DC approximation specified? Is there an easy way to fix this or specify the objective? I am new to Julia and I find it a bit hard to play around with all the options. The documentation in terms of examples and options seems limited. It is much easier to have examples illustrating the options rather than searching for each option in a long .pdf documentation. For example I had to search a lot in Tulip's documentation to find how could I set parameters to Tulip such as OutputLevel=1 although this is very basic and should be on by default. 

Thank you for your time and the excellent software!

**Comment by ccoffrin** [comment]
Many OPF datasets feature generators with quadratic cost functions, which makes a DC-OPF a QP instead of an LP. The fix in this case is to use a solver that support QP models. The solver HiGHS is a popular open source option these days.  You could also change the dataset to make the generator cost functions linear.

If you would like Tulip to support QP (not just LP) or would suggest different default settings, I suggest you post an issue for that solver, https://github.com/ds4dm/Tulip.jl

Also, for the fastest response I suggest posting questions like these to the Julia forms in the Optimization category, https://discourse.julialang.org/c/domain/opt/13

**Comment by DimaLPorNLP** [comment]
Hi Carleton,
thanks for the info. So I see! You decided to respect the objective function as is despite the user desire to solve an LP. Usually in Power Systems when people go DC they linearize all the way. It does not make sense to mix things. What you describe would require another function call something like `DCQPPowerModel`, or other linearizations assuming linear or quadratic objectives. Alternatively, one could change the Abstract class allowing for an additional argument something like an enumerated type representing the objective type (quadratic or linear or something else). Something like: 

`solve_opf("case.m", DCPPowerModel, LINEAR_OBJECTIVE)`

What do you think?
All best!

P.S. I was under the impression that this forum is for people using PowerModels and other forums like the one you mentioned is for general users of optimization packages in Julia who are not necessarily familiar with Power Systems and PowerModels.

**Comment by ccoffrin** [comment]
The approach of PowerModels is to leave these choices to the user through manipulation of the data file.  This has been working well for many years so we will keep it this way.

**Comment by DimaLPorNLP** [comment]
I see, but since the documentation is not complete in the sense that there are is not a single complete example explaining how a PowerModel optimization problem is set up, starting from loading the case file, defining constraints, defining objective, solve all the benefits that come from the "quick start" functions `solve_opf(case, model, LP or NLP_solver)` are gone. It could be much more flexible to allow an additional argument specifying the type of the objective. Otherwise all the beautiful abstractions included in the aforementioned classes need to be repeated by the user for what? For just changing the objective? The flexibility of all that effort in beautiful design is suddenly gone. And then the question rises, what was the purpose of all this beauty? Just to compare different power models that have appeared in the literature quickly and easy and decide which is the best one?
