### ISSUE TITLE
Creating Result dict from JuMP model

### ISSUE THREAD

**Issue by desantikuleuven** [lanl-ansi/PowerModels.jl#857]
Hello,
I have created my own DCPF JuMP model, following what was suggested also on PowerModelsAnnex.jl.
Once the model is optimized, I need to store the variables values in a Dict which has the same structure as the result Dict from PowerModels.jl. 

An example of what I do for storing generation values "pg"  for every hour and every day of the simulation is for instance

	representative_days = [11, 57]
	AGG_NET_DATA = Dict{Int64, Any}()   #Aggregate net data

	for day in representative_days
		mn_net_data = create_multi_net_data(net_data, day) # gives back a mnultinetwork data with values tuned for the specific day 
		push!(AGG_NET_DATA, repr_day => mn_net_data)  #store for each day the different multi_network_data 
	end
	
	# solve model
	model = solve_yearly_model_dc(AGG_NET_DATA, "mn_optimal_dc_loc_v3")	

	# create a big result dict for every representative day. The values should then have the typical result dict format
	AGG_RESULT = Dict(day => Dict() for day in keys(AGG_NET_DATA))   

	# create ref for each day 
	AGG_REF = Dict( day => Dict{Any,Any}() for day in keys(agg_net_data))
    	for (repr_day, data) in agg_net_data
       		ref[repr_day] = PowerModels.build_ref(AGG_NET_DATA, [repr_day])[:it][:pm]
    	end

	for (day, ref) in AGG_REF

		hours = keys(ref[:nw])
		# create the typical syntax from PowerModels for multinetowrk results 
		result = Dict("solution" => Dict("nw" => Dict(h => Dict() for h in string.(hours))),
       	                 "termination_status" => [], "objective" => Float64, "per_unit" => true
        	)
	
		# populate result entries with pg values. pg is a JuMP varibale with three indexes (generator_id, hour of the day, representative day) 
		for h in hours 
			result["solution"]["nw"][h]["gen"] = Dict{String, Any}(idx => Dict("pg" => value.(model[:pg])[idx,h,day]) for idx in keys(ref[:nw][h][:gen]))
		end
		
		result["termination_status"] = termination_status(model)
        	result["objective"] = objective_value(model)

		AGG_RESULT[day] = result
	end

So far my approach takes a long time once the loop to populate the AGG_RESULT is started, I wonder if there is a more efficient approach that could be adopted. 
Thank you for your help

**Comment by ccoffrin** [comment]
I don't have any specific suggestions for you other than reposting this question in the Julia forums, https://discourse.julialang.org/c/domain/opt/13

I am closing this issue because there is nothing actionable to do in PowerModels it self.
