### ISSUE TITLE
SDP

### ISSUE THREAD

**Issue by lzq-zbc** [lanl-ansi/PowerModels.jl#864]
I want to use the ECOS solver to solve some errors in the SDP model in OPF.
`using JuMP, PowerModels, Ipopt,ECOS

file_name = "E:/Vscode——data/data/case5.m"
# file_name = "E:/Vscode——data/data/case9.m"
# file_name = "E:/Vscode——data/data/case14.m"
# file_name = "E:/Vscode——data/data/case18.m"
# file_name = "E:/Vscode——data/data/case24_ieee_rts.m"
# file_name = "E:/Vscode——data/data/case30.m"
# file_name = "E:/Vscode——data/data/case39.m"
# file_name = "E:/Vscode——data/data/case57.m"
# file_name = "E:/Vscode——data/data/case118.m"
# file_name = "E:/Vscode——data/data/case300.m"
# file_name = "E:/Vscode——data/data/case_ACTIVSg500.m"
# file_name = "E:/Vscode——data/data/case2736sp.m"

model = Model(ECOS.Optimizer)
power_model = PowerModels.instantiate_model(
    PowerModels.parse_file(file_name),
    PowerModels.SDPWRMPowerModel,
    PowerModels.build_opf;
    jump_model = model,
)
optimize!(model)
println("Optimal objective value: ", JuMP.objective_value(model))`

The following is the error reported：

`ERROR: `MOI.VectorAffineFunction{Float64}`-in-`MOI.PositiveSemidefiniteConeSquare` constraints are not supported and cannot be bridged into supported constrained variables and constraints. See details below:
 [6] constrained variables in `MOI.PositiveSemidefiniteConeSquare` are not supported because no added bridge supports bridging it.
   Cannot add free variables and then constrain them because:
   (12) `MOI.VectorOfVariables`-in-`MOI.PositiveSemidefiniteConeSquare` constraints are not supported
 [7] constrained variables in `MOI.PositiveSemidefiniteConeTriangle` are not supported because no added bridge supports bridging it.
   Cannot add free variables and then constrain them because:
   (13) `MOI.VectorOfVariables`-in-`MOI.PositiveSemidefiniteConeTriangle` constraints are not supported
 (11) `MOI.VectorAffineFunction{Float64}`-in-`MOI.PositiveSemidefiniteConeSquare` constraints are not supported because:
   Cannot use `MOIB.Constraint.VectorSlackBridge{Float64, MOI.VectorAffineFunction{Float64}, MOI.PositiveSemidefiniteConeSquare}` because:
   [6] constrained variables in `MOI.PositiveSemidefiniteConeSquare` are not supported
   Cannot use `MOIB.Constraint.SquareBridge{Float64, MOI.VectorAffineFunction{Float64}, MOI.ScalarAffineFunction{Float64}, MOI.PositiveSemidefiniteConeTriangle, MOI.PositiveSemidefiniteConeSquare}` because:
   (14) `MOI.VectorAffineFunction{Float64}`-in-`MOI.PositiveSemidefiniteConeTriangle` constraints are not supported
 (12) `MOI.VectorOfVariables`-in-`MOI.PositiveSemidefiniteConeSquare` constraints are not supported because:
   Cannot use `MOIB.Constraint.VectorFunctionizeBridge{Float64, MOI.PositiveSemidefiniteConeSquare}` because:
   (11) `MOI.VectorAffineFunction{Float64}`-in-`MOI.PositiveSemidefiniteConeSquare` constraints are not supported
   Cannot use `MOIB.Constraint.SquareBridge{Float64, MOI.VectorOfVariables, MOI.ScalarAffineFunction{Float64}, MOI.PositiveSemidefiniteConeTriangle, MOI.PositiveSemidefiniteConeSquare}` because:
   (13) `MOI.VectorOfVariables`-in-`MOI.PositiveSemidefiniteConeTriangle` constraints are not supported
 (13) `MOI.VectorOfVariables`-in-`MOI.PositiveSemidefiniteConeTriangle` constraints are not supported because:
   Cannot use `MOIB.Constraint.VectorFunctionizeBridge{Float64, MOI.PositiveSemidefiniteConeTriangle}` because:
   (14) `MOI.VectorAffineFunction{Float64}`-in-`MOI.PositiveSemidefiniteConeTriangle` constraints are not supported
 (14) `MOI.VectorAffineFunction{Float64}`-in-`MOI.PositiveSemidefiniteConeTriangle` constraints are not supported because:
   Cannot use `MOIB.Constraint.VectorSlackBridge{Float64, MOI.VectorAffineFunction{Float64}, MOI.PositiveSemidefiniteConeTriangle}` because:
   [7] constrained variables in `MOI.PositiveSemidefiniteConeTriangle` are not supported`

**Comment by ccoffrin** [comment]
This has been answered here, https://discourse.julialang.org/t/about-using-powermodels-to-solve-problems-with-sdp-opf/99750/2

Posting these types of questions to Julia discourse is the best option for the fastest response.
