### ISSUE TITLE
Undefined variables in function calc_theta_delta_bounds

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/PowerModels.jl#870]
In function calc_theta_delta_bounds, when the function drops into line 76, it references undefined variables amin and amax and throws an UndefVarError

**Comment by ccoffrin** [comment]
Good catch.  I have merged a test and a fix, do you need a new release tagged right away?

On a side note, this example made me realize there is a bunch of "conductor" based features that could probably be removed from PM now that PMD is basically a stand alone package.  Do you see a reason to keep supporting "conductors" in PM?

CC @pseudocubic

**Comment by rb004f** [comment]
No, I don't need a new release right away.  And yes, it seems like we are migrating away from having multi conductor support in PowerModels and have it all in PMD.
