### ISSUE TITLE
Drop Multiconductor Support

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#872]
Verify this feature is not required and if so, drop support for it.

**Comment by ccoffrin** [comment]
@pseudocubic do you see any reason to keep this feature around in PM?

I belive PMD is not totally independent from PM, right?

**Comment by rb004f** [comment]
Best I can tell, PM is not listed as a dependency for PMD in the project.toml

**Comment by pseudocubic** [comment]
@ccoffrin no, I don't see a reason to keep around references to conductors here anymore, and in fact the referenced code likely wouldn't work in PMD today.

**Comment by ccoffrin** [comment]
Indeed. I am intrigued by the circumstance that @rb004f had run into the broken control path in #870

**Comment by rb004f** [comment]
PowerModelsONM -> PowerModelsProtection -> PowerModels
                                                                         -> PowerModelsDistribution
