### ISSUE TITLE
Installation of PowerModels with Ipopt support fails on MUSL based systems (Alpine) due to Ipopt

### ISSUE THREAD

**Issue by DoctorDro** [lanl-ansi/PowerModels.jl#904]
Dear all,
trying to install PowerModels and Ipopt on Latest Julia 10 under Alpine Linux failed because Ipopt cannot be installed there. Ipopt fails due to shared libraries such as libmetis.so cannot be loaded. 
```
ERROR: LoadError: InitError: could not load library "/home/Dr2Dr/.julia/artifacts/056dc52f41656651083a0a7a46b9d87e9ada7ff9/lib/libcmumps.so"
Error loading shared library libmetis.so: No such file or directory (needed by /home/Dr2Dr/.julia/artifacts/056dc52f41656651083a0a7a46b9d87e9ada7ff9/lib/libcmumps.so)
```
Trying to create symbolic links where Ipopt expects libmetis.so revealed that other libraries such as spral dependencies could not be found due to the same reason. Then creating again symbolic links revealed that other libraries such as libipoptamplinterface.so could not be loaded and so on ...

Any ideas why that could be happening only on musl linux systems and not on any other Windows, Linux or FreeBSD?

**Comment by odow** [comment]
Let's close this in favor of the ones in Ipopt.jl.
