### ISSUE TITLE
Potential bug in on_off constraints for dcp.jl

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/PowerModels.jl#907]
The on off and ne constraints for dcp utilize vad_max and vad_min as big M values to turn off various constraints, see for example
 
if b <= 0
   JuMP.@constraint(pm.model, p_fr <= -b*(va_fr - va_to + vad_max*(1-z)) )
   JuMP.@constraint(pm.model, p_fr >= -b*(va_fr - va_to + vad_min*(1-z)) )
...

in constraint_ohms_yt_from_on_off.  vad_max and vad_min need to be sufficiently large so that p_fr can take value 0 when z =1.  At the moment vad_max and vad_min are calculated as the single largest phase angle difference of any line (function calc_theta_delta_bounds), however, this does not appear to guarantee that this will be sufficiently large in all cases.  Consider the contrived corner case where all phase angle difference maxes for lines are 0, and va_fr < va_to on the turned off line. This will force p_fr < 0.  I believe that vad_max needs to be the max of the sum angmax of any path between i and j (which is computationally inefficient to compute) or at least the sum of  all angmax differences on lines

It looks like calc_theta_delta_bounds may have done this in previous versions, where this undocumented change was introduced between version 19.10 and version 20.

Side note: calc_theta_delta_bounds is using an n log n call find the max angmax (sort) when this could be done in linear time.

**Comment by noahrhodes** [comment]
Looking at the version in 19.10, it looks like it was a bit more intelligent than summing all angle bounds without calculating a longest path for each pair of nodes:
 - A longest path in the network will visit at most all `N` nodes and travel along N-1 edges
 - Get a list of the `N-1` largest angle differences in the network
 - Return the sum of these angle differences 
 
This is done for each conductor in the system, if there is only one conductor return a single value instead (index 1)

Now, it returns the first line's max angle difference.  

https://github.com/lanl-ansi/PowerModels.jl/blob/010b6ee972ab090212f0528f807b368b7f697c59/src/core/data.jl#L37

**Comment by rb004f** [comment]
Yes, I agree, that is a smaller (valid) bound. It looks like the bug might have been introduced when support was dropped for multiple conductors in v20. Which would explain why the (currently) orphaned bus_count variable is there and why a sort was required.

**Comment by ccoffrin** [comment]
I concur this is a bug that was introduced between v19 and v20. I am a bit shocked that no test caught it! A new test the illicits the issue would be helpful.

The missing code is,
```
        if length(angle_mins) > 1
            # note that, this can occur when dclines are present
            angle_count = min(bus_count-1, length(branches))

            angle_min_val = sum(angle_mins[1:angle_count])
            angle_max_val = sum(angle_maxs[1:angle_count])
        else
            angle_min_val = angle_mins[1]
            angle_max_val = angle_maxs[1]
        end
```

I probably won't be able to fix for a couple of days.

**Comment by rb004f** [comment]
Maybe explicit tests to check on calc_theta_bounds for values we calculate once the fix is in place.  I suspect for all the tests passed because the ang_max was sufficiently large (probably pi/2) that it didn't artificially constrain anything in typical networks.  You need a really contrived case to get a larger angle difference between buses that can be disconnected by a switch. Or large n-k failures (which is the use case where we found the bug)

**Comment by ccoffrin** [comment]
Thanks for the find @rb004f.

A interesting anecdote, there was a test for this function as part of the multi-conductor test.  When I removed that feature I also dropped that test, which allowed this bug to creep in.
