### ISSUE TITLE
Documentation: DCPPowerModel description text

### ISSUE THREAD

**Issue by KSepetanc** [lanl-ansi/PowerModels.jl#910]
Formula in the description of DC model appears to mistyped:
[link](https://lanl-ansi.github.io/PowerModels.jl/stable/formulation-details/#PowerModels.ACRPowerModel)
`br_b = -br_x / (br_x^2 + br_x^2)`

Instead I think it should be:
`br_b = -br_x / (br_x^2 + br_r^2)`

Can we fix this?

**Comment by odow** [comment]
I don't think the link you've provided is correct?

I see:

![image](https://github.com/lanl-ansi/PowerModels.jl/assets/8177701/e29b1161-5e35-42b2-bd7c-79e32c499736)

**Comment by odow** [comment]
See https://github.com/lanl-ansi/PowerModels.jl/pull/911

**Comment by KSepetanc** [comment]
Fixed the link. Thanks for fixing.
