### ISSUE TITLE
PSSE Parser: incorrect impedance when NOMVX is 0.0 

### ISSUE THREAD

**Issue by frederikgeth** [lanl-ansi/PowerModels.jl#912]
Ran into this bug with @hei06j while parsing 3-winding transformers from PSSE.

Per the PSSE Manual on NOMV1, NOMV2, NOMV3: 
> The nominal (rated) winding one voltage in kV, or zero to indicate that nominal winding one voltage is to be taken as the base voltage of bus "I". NOMV1 is used only in converting magnetizing data between per unit admittance values and physical units when CM is 2. NOMV1 = 0.0 by default.

If that happens, the transformer impedances get accidentally set to 0 [here](https://github.com/lanl-ansi/PowerModels.jl/blob/8e346b48c187b2a53907dc031603482f2e6a2017/src/io/psse.jl#L437)
```julia
br_r *= (transformer["NOMV1"]^2 / _get_bus_value(transformer["I"], "base_kv", pm_data)^2) * (pm_data["baseMVA"] / transformer["SBASE1-2"])
br_x *= (transformer["NOMV1"]^2 / _get_bus_value(transformer["I"], "base_kv", pm_data)^2) * (pm_data["baseMVA"] / transformer["SBASE1-2"])
```
This should be replaced with something like
```julia
if transformer["NOMV1"] == 0.0
  br_r *= (pm_data["baseMVA"] / transformer["SBASE1-2"])
  br_x *= (pm_data["baseMVA"] / transformer["SBASE1-2"])
else
  br_r *= (transformer["NOMV1"]^2 / _get_bus_value(transformer["I"], "base_kv", pm_data)^2) * (pm_data["baseMVA"] / transformer["SBASE1-2"])
  br_x *= (transformer["NOMV1"]^2 / _get_bus_value(transformer["I"], "base_kv", pm_data)^2) * (pm_data["baseMVA"] / transformer["SBASE1-2"])
end
```

**Comment by frederikgeth** [comment]
Just saw Jay's issue and I think it is the same underlying issue, https://github.com/lanl-ansi/PowerModels.jl/issues/888, which ran into this problem for branches, not (3-winding) transformers

Note that with r and x both effectively becoming zero none of the bus injection model type formulations will work, and instead converge to an infeasible point.

**Comment by ccoffrin** [comment]
Can you adapt one of the test network datasets to exhibit the issue so that we can make a test for this?

**Comment by frederikgeth** [comment]
We have a MWE with PSSE baseline results, @hei06j started preparing a PR. Hopefully we can get it out today before flying to PSCC.

**Comment by ccoffrin** [comment]
Has this been addressed by https://github.com/lanl-ansi/PowerModels.jl/pull/919?

**Comment by hei06j** [comment]
Yes.
