### ISSUE TITLE
Performance of make_basic_network

### ISSUE THREAD

**Issue by mtanneau** [lanl-ansi/PowerModels.jl#913]
The `make_basic_network` function is slow for large networks.
The timings below were obtained with `@time make_basic_network(data)` where `data` was loaded with the PGLib package.

| Case | #buses | time (s) | memory (MiB) |
|:--|--:|--:|--:|
| `1354_pegase` | 1354 | 0.21 | 28.5 |
| `2869_pegase` | 2869 | 0.62 | 66.8 |
| `9241_pegase` | 9241 | 2.50 | 208.4 |
| `13659_pegase` | 13659 | 5.72 | 303.1 |
| `30000_goc` | 30000 | 15.81 | 467.8 |

I profiled it on the `9241_pegase` case:
![prof_old](https://github.com/lanl-ansi/PowerModels.jl/assets/9593025/9b595704-f031-4f1b-97ef-be101139ee1f)

which shows that, besides an initial `deepcopy` which we can't do much about, a substantial amount of time is spent identifying connected components.
Note that the very high stacktrace with `_cc_dfs` corresponds to recursive calls to a DFS implementation [here](https://github.com/lanl-ansi/PowerModels.jl/blob/8e346b48c187b2a53907dc031603482f2e6a2017/src/core/data.jl#L2547-L2560).

PR coming

**Comment by mtanneau** [comment]
@ccoffrin I have opened two PRs to address the initial deepcopy (#915) and the identification of connected components (#914).

The 3rd room for performance improvement is within [`_renumber_components`](https://github.com/lanl-ansi/PowerModels.jl/blob/8e346b48c187b2a53907dc031603482f2e6a2017/src/core/data_basic.jl#L151-L163), which contains a lot of `deepcopy`s itself.
Namely, all individual components are deepcopied before being re-numbered.

I believe this is not necessary, since we deepcopy the initial data dictionary, and everything afterwards modifies the data dict in-place. As far as I can see, `_renumber_components` is only called inside `make_basic_network`, so eliminating the deepcopy below would save further time and memory
https://github.com/lanl-ansi/PowerModels.jl/blob/8e346b48c187b2a53907dc031603482f2e6a2017/src/core/data_basic.jl#L156-L160

**Comment by ccoffrin** [comment]
Has this been addressed by https://github.com/lanl-ansi/PowerModels.jl/pull/919?

**Comment by mtanneau** [comment]
Yes!

For completeness, I re-ran the timings and profiles; results are below.

___

New timing table on `master` for `make_basic_network`:

| Case | #buses | time (s) | memory (MiB) |
|:--|--:|--:|--:|
| `1354_pegase` |   1354 |   0.13 |   20.1 |
| `2869_pegase` |   2869 |   0.29 |   45.7 |
| `9241_pegase` |   9241 |   1.09 |  137.1 |
| `13659_pegase` |  13659 |   1.47 |  215.5 |
| `30000_goc` |  30000 |   2.53 |  320.1 |

and corresponding profile on 9k Pegase system
![prof_master](https://github.com/lanl-ansi/PowerModels.jl/assets/9593025/cbaeec2a-9b92-427f-a908-dd8e78fa42b9)


___

Same, but for the in-place `make_basic_network!`:

| Case | #buses | time (s) | memory (MiB) |
|:--|--:|--:|--:|
| `1354_pegase` |   1354 |   0.05 |   11.0 |
| `2869_pegase` |   2869 |   0.13 |   27.2 |
| `9241_pegase` |   9241 |   0.47 |   74.7 |
| `13659_pegase` |  13659 |   0.70 |  130.0 |
| `30000_goc` |  30000 |   1.27 |  181.6 |

and corresponding profile on 9k Pegase system

![prof_master](https://github.com/lanl-ansi/PowerModels.jl/assets/9593025/7e9d0c73-698a-43a3-aae4-e1477bea3d92)
