### ISSUE TITLE
Add Storage Variables in build_opf

### ISSUE THREAD

**Issue by BeccyGitHub** [lanl-ansi/PowerModels.jl#926]
Currently, PowerModels gives an error like "does not find active power of storage", so it cannot do the OPF computation.

I added the already existing function "variable_storage_power(pm)" in "opf.jl/build_opf", which is working. 
I'm just not sure if it needs to be added anywhere else.

Could you add that in the repo? Thanks!

**Comment by ccoffrin** [comment]
You should call one of these OPF variants to consider the storage data, https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/prob/test.jl#L402-L495

In the modeling layer you need to add both the storage variables but also the constraints.

**Comment by BeccyGitHub** [comment]
Thanks! It's weird.. I called "_solve_opf_str" and I see that in "PowerModels/Dhfhc/src/prob/test.jl" it uses the "_build_opf_strg", but somehow it used "build_opf" instead.. Now it miraculously works though!
